//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_preview_training__graphcall__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx_preview_training__graphcall__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_Inputs = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_Inputs);

    // Onnx__AttributeProto *a_graph_name = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"graph_name");

    // TRACE_ATTRIBUTE(2, true, a_graph_name);

    // Onnx__TensorProto *o_Outputs = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    

    // context_operator__ai_onnx_preview_training__graphcall__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx_preview_training__graphcall__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->graph_name = strndup(a_graph_name->s.data, a_graph_name->s.len);
    // TRACE_FATAL(0, !op_ctx->graph_name, "malloc failed");

    // TRACE_VAR(2, true, op_ctx->graph_name, "\"%s\"");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Outputs);

    // TRACE_TENSOR(2, true, o_Outputs);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx_preview_training__graphcall__1(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}