//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__reducemin__1;
extern operator_set_opversion opversion_operator__ai_onnx__reducemin__11;
extern operator_set_opversion opversion_operator__ai_onnx__reducemin__12;

operator_set_opname opname_operator__ai_onnx__reducemin = {
    .name = "ReduceMin",
    .opversions = {
        &opversion_operator__ai_onnx__reducemin__1,
        &opversion_operator__ai_onnx__reducemin__11,
        &opversion_operator__ai_onnx__reducemin__12,
        NULL
    }
};