//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__tfidfvectorizer__9.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__tfidfvectorizer__9__T_tensor_int64(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx__tfidfvectorizer__9 *op_ctx = ctx->executer_context;

    // int64_t max_gram_length = op_ctx->max_gram_length;
    // int64_t max_skip_count = op_ctx->max_skip_count;
    // int64_t min_gram_length = op_ctx->min_gram_length;
    // char* mode = op_ctx->mode;
    // size_t n_ngram_counts = op_ctx->n_ngram_counts;
    // int64_t* ngram_counts = op_ctx->ngram_counts;
    // size_t n_ngram_indexes = op_ctx->n_ngram_indexes;
    // int64_t* ngram_indexes = op_ctx->ngram_indexes;
    // size_t n_pool_int64s = op_ctx->n_pool_int64s;
    // int64_t* pool_int64s = op_ctx->pool_int64s;
    // size_t n_pool_strings = op_ctx->n_pool_strings;
    // char** pool_strings = op_ctx->pool_strings;
    // size_t n_weights = op_ctx->n_weights;
    // float* weights = op_ctx->weights;

    // TRACE_VAR(2, true, max_gram_length, "%" PRId64);
    // TRACE_VAR(2, true, max_skip_count, "%" PRId64);
    // TRACE_VAR(2, true, min_gram_length, "%" PRId64);
    // TRACE_VAR(2, true, mode, "\"%s\"");
    // TRACE_ARRAY(2, true, ngram_counts, , n_ngram_counts, "%" PRId64);
    // TRACE_ARRAY(2, true, ngram_indexes, , n_ngram_indexes, "%" PRId64);
    // TRACE_ARRAY(2, true, pool_int64s, , n_pool_int64s, "%" PRId64);
    // TRACE_ARRAY(2, true, pool_strings, , n_pool_strings, "\"%s\"");
    // TRACE_ARRAY(2, true, weights, , n_weights, "%f");

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}