//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__tfidfvectorizer__9.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__tfidfvectorizer__9(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_max_gram_length = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"max_gram_length");
    // Onnx__AttributeProto *a_max_skip_count = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"max_skip_count");
    // Onnx__AttributeProto *a_min_gram_length = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"min_gram_length");
    // Onnx__AttributeProto *a_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"mode");
    // Onnx__AttributeProto *a_ngram_counts = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"ngram_counts");
    // Onnx__AttributeProto *a_ngram_indexes = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"ngram_indexes");
    // Onnx__AttributeProto *a_pool_int64s = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"pool_int64s");
    // Onnx__AttributeProto *a_pool_strings = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"pool_strings");
    // Onnx__AttributeProto *a_weights = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"weights");

    // TRACE_ATTRIBUTE(2, true, a_max_gram_length);
    // TRACE_ATTRIBUTE(2, true, a_max_skip_count);
    // TRACE_ATTRIBUTE(2, true, a_min_gram_length);
    // TRACE_ATTRIBUTE(2, true, a_mode);
    // TRACE_ATTRIBUTE(2, true, a_ngram_counts);
    // TRACE_ATTRIBUTE(2, true, a_ngram_indexes);
    // TRACE_ATTRIBUTE(2, a_pool_int64s, a_pool_int64s);
    // TRACE_ATTRIBUTE(2, a_pool_strings, a_pool_strings);
    // TRACE_ATTRIBUTE(2, a_weights, a_weights);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // size_t default_n_pool_int64s = ;
    // int64_t* default_pool_int64s = ;
    // size_t default_n_pool_strings = ;
    // char** default_pool_strings = ;
    // size_t default_n_weights = ;
    // float* default_weights = ;

    // context_operator__ai_onnx__tfidfvectorizer__9 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__tfidfvectorizer__9));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->max_gram_length = a_max_gram_length->i;
    // op_ctx->max_skip_count = a_max_skip_count->i;
    // op_ctx->min_gram_length = a_min_gram_length->i;
    // op_ctx->mode = strndup(a_mode->s.data, a_mode->s.len);
    // TRACE_FATAL(0, !op_ctx->mode, "malloc failed");
    // op_ctx->n_ngram_counts = a_ngram_counts->n_ints;
    // op_ctx->ngram_counts = a_ngram_counts->ints;
    // op_ctx->n_ngram_indexes = a_ngram_indexes->n_ints;
    // op_ctx->ngram_indexes = a_ngram_indexes->ints;
    // op_ctx->n_pool_int64s = a_pool_int64s?a_pool_int64s->n_ints:default_n_pool_int64s;
    // op_ctx->pool_int64s = a_pool_int64s?a_pool_int64s->ints:ARRAYDUP(default_pool_int64s,default_n_pool_int64s);
    // TRACE_FATAL(0, !op_ctx->pool_int64s, "malloc failed");
    // op_ctx->n_pool_strings = a_pool_strings?a_pool_strings->n_strings:default_n_pool_strings;
    // if (a_pool_strings) {
    //     op_ctx->pool_strings = malloc(a_pool_strings->n_strings * sizeof(char*));
    //     TRACE_FATAL(0, !op_ctx->pool_strings, "malloc failed");
    //     for (int i = 0; i < a_pool_strings->n_strings; i++) { op_ctx->pool_strings[i] = strndup((char*)a_pool_strings->strings[i].data, a_pool_strings->strings[i].len); }
    // } else {
    //     op_ctx->pool_strings = a_pool_strings?a_pool_strings->strings:ARRAYDUP(default_pool_strings,default_n_pool_strings);
    //     TRACE_FATAL(0, !op_ctx->pool_strings, "malloc failed");
    // }
    // op_ctx->n_weights = a_weights?a_weights->n_floats:default_n_weights;
    // op_ctx->weights = a_weights?a_weights->floats:ARRAYDUP(default_weights,default_n_weights);
    // TRACE_FATAL(0, !op_ctx->weights, "malloc failed");

    // TRACE_VAR(2, true, op_ctx->max_gram_length, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->max_skip_count, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->min_gram_length, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->mode, "\"%s\"");
    // TRACE_ARRAY(2, true, op_ctx->ngram_counts, , op_ctx->n_ngram_counts, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->ngram_indexes, , op_ctx->n_ngram_indexes, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->pool_int64s, , op_ctx->n_pool_int64s, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->pool_strings, , op_ctx->n_pool_strings, "\"%s\"");
    // TRACE_ARRAY(2, true, op_ctx->weights, , op_ctx->n_weights, "%f");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Y);

    // TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx__tfidfvectorizer__9(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}