//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__sequencelength__11.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__sequencelength__11(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_input_sequence = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_input_sequence);

    

    

    //Onnx__TensorProto *o_length = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_length);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__sequencelength__11 *op_ctx = ctx->executer_context;

    

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_length);
    // free(o_length->dims);

    TRACE_EXIT(1);
}