//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__qlinearconv__10.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__qlinearconv__10__T1_tensor_int8__T2_tensor_uint8__T3_tensor_int8__T4_tensor_int32(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_x = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_x_scale = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_x_zero_point = searchInputByName(ctx, 2);
    // Onnx__TensorProto *i_w = searchInputByName(ctx, 3);
    // Onnx__TensorProto *i_w_scale = searchInputByName(ctx, 4);
    // Onnx__TensorProto *i_w_zero_point = searchInputByName(ctx, 5);
    // Onnx__TensorProto *i_y_scale = searchInputByName(ctx, 6);
    // Onnx__TensorProto *i_y_zero_point = searchInputByName(ctx, 7);
    // Onnx__TensorProto *i_B = searchInputByName(ctx, 8);

    // TRACE_TENSOR(2, true, i_x);
    // TRACE_TENSOR(2, true, i_x_scale);
    // TRACE_TENSOR(2, true, i_x_zero_point);
    // TRACE_TENSOR(2, true, i_w);
    // TRACE_TENSOR(2, true, i_w_scale);
    // TRACE_TENSOR(2, true, i_w_zero_point);
    // TRACE_TENSOR(2, true, i_y_scale);
    // TRACE_TENSOR(2, true, i_y_zero_point);
    // TRACE_TENSOR(2, B, i_B);

    // context_operator__ai_onnx__qlinearconv__10 *op_ctx = ctx->executer_context;

    // char* auto_pad = op_ctx->auto_pad;
    // size_t n_dilations = op_ctx->n_dilations;
    // int64_t* dilations = op_ctx->dilations;
    // int64_t group = op_ctx->group;
    // size_t n_kernel_shape = op_ctx->n_kernel_shape;
    // int64_t* kernel_shape = op_ctx->kernel_shape;
    // size_t n_pads = op_ctx->n_pads;
    // int64_t* pads = op_ctx->pads;
    // size_t n_strides = op_ctx->n_strides;
    // int64_t* strides = op_ctx->strides;

    // TRACE_VAR(2, true, auto_pad, "\"%s\"");
    // TRACE_ARRAY(2, true, dilations, , n_dilations, "%" PRId64);
    // TRACE_VAR(2, true, group, "%" PRId64);
    // TRACE_ARRAY(2, true, kernel_shape, , n_kernel_shape, "%" PRId64);
    // TRACE_ARRAY(2, true, pads, , n_pads, "%" PRId64);
    // TRACE_ARRAY(2, true, strides, , n_strides, "%" PRId64);

    // Onnx__TensorProto *o_y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}