//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__size__1;

operator_set_opname opname_operator__ai_onnx__size = {
    .name = "Size",
    .opversions = {
        &opversion_operator__ai_onnx__size__1,
        NULL
    }
};