//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__scan__8;
extern operator_set_opversion opversion_operator__ai_onnx__scan__9;
extern operator_set_opversion opversion_operator__ai_onnx__scan__11;

operator_set_opname opname_operator__ai_onnx__scan = {
    .name = "Scan",
    .opversions = {
        &opversion_operator__ai_onnx__scan__8,
        &opversion_operator__ai_onnx__scan__9,
        &opversion_operator__ai_onnx__scan__11,
        NULL
    }
};