//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__linearregressor__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx_ml__linearregressor__1__T_tensor_double(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx_ml__linearregressor__1 *op_ctx = ctx->executer_context;

    // size_t n_coefficients = op_ctx->n_coefficients;
    // float* coefficients = op_ctx->coefficients;
    // size_t n_intercepts = op_ctx->n_intercepts;
    // float* intercepts = op_ctx->intercepts;
    // char* post_transform = op_ctx->post_transform;
    // int64_t targets = op_ctx->targets;

    // TRACE_ARRAY(2, true, coefficients, , n_coefficients, "%f");
    // TRACE_ARRAY(2, true, intercepts, , n_intercepts, "%f");
    // TRACE_VAR(2, true, post_transform, "\"%s\"");
    // TRACE_VAR(2, true, targets, "%" PRId64);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}