//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__linearregressor__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx_ml__linearregressor__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_coefficients = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"coefficients");
    // Onnx__AttributeProto *a_intercepts = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"intercepts");
    // Onnx__AttributeProto *a_post_transform = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"post_transform");
    // Onnx__AttributeProto *a_targets = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"targets");

    // TRACE_ATTRIBUTE(2, a_coefficients, a_coefficients);
    // TRACE_ATTRIBUTE(2, a_intercepts, a_intercepts);
    // TRACE_ATTRIBUTE(2, a_post_transform, a_post_transform);
    // TRACE_ATTRIBUTE(2, a_targets, a_targets);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // size_t default_n_coefficients = ;
    // float* default_coefficients = ;
    // size_t default_n_intercepts = ;
    // float* default_intercepts = ;
    // char* default_post_transform = ;
    // int64_t default_targets = ;

    // context_operator__ai_onnx_ml__linearregressor__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx_ml__linearregressor__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->n_coefficients = a_coefficients?a_coefficients->n_floats:default_n_coefficients;
    // op_ctx->coefficients = a_coefficients?a_coefficients->floats:ARRAYDUP(default_coefficients,default_n_coefficients);
    // TRACE_FATAL(0, !op_ctx->coefficients, "malloc failed");
    // op_ctx->n_intercepts = a_intercepts?a_intercepts->n_floats:default_n_intercepts;
    // op_ctx->intercepts = a_intercepts?a_intercepts->floats:ARRAYDUP(default_intercepts,default_n_intercepts);
    // TRACE_FATAL(0, !op_ctx->intercepts, "malloc failed");
    // op_ctx->post_transform = a_post_transform?strndup((char*)a_post_transform->s.data, a_post_transform->s.len):default_post_transform;
    // op_ctx->targets = a_targets?a_targets->i:default_targets;

    // TRACE_ARRAY(2, true, op_ctx->coefficients, , op_ctx->n_coefficients, "%f");
    // TRACE_ARRAY(2, true, op_ctx->intercepts, , op_ctx->n_intercepts, "%f");
    // TRACE_VAR(2, true, op_ctx->post_transform, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->targets, "%" PRId64);

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Y);

    // TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx_ml__linearregressor__1(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}