//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__imputer__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx_ml__imputer__1__T_tensor_int64(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx_ml__imputer__1 *op_ctx = ctx->executer_context;

    // size_t n_imputed_value_floats = op_ctx->n_imputed_value_floats;
    // float* imputed_value_floats = op_ctx->imputed_value_floats;
    // size_t n_imputed_value_int64s = op_ctx->n_imputed_value_int64s;
    // int64_t* imputed_value_int64s = op_ctx->imputed_value_int64s;
    // float replaced_value_float = op_ctx->replaced_value_float;
    // int64_t replaced_value_int64 = op_ctx->replaced_value_int64;

    // TRACE_ARRAY(2, true, imputed_value_floats, , n_imputed_value_floats, "%f");
    // TRACE_ARRAY(2, true, imputed_value_int64s, , n_imputed_value_int64s, "%" PRId64);
    // TRACE_VAR(2, true, replaced_value_float, "%f");
    // TRACE_VAR(2, true, replaced_value_int64, "%" PRId64);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}