//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__einsum__12.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__einsum__12(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_Inputs = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_Inputs);

    // Onnx__AttributeProto *a_equation = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"equation");

    // TRACE_ATTRIBUTE(2, true, a_equation);

    Onnx__TensorProto *o_Output = searchOutputByIndex(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    

    // context_operator__ai_onnx__einsum__12 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__einsum__12));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->equation = strndup(a_equation->s.data, a_equation->s.len);
    // TRACE_FATAL(0, !op_ctx->equation, "malloc failed");

    // TRACE_VAR(2, true, op_ctx->equation, "\"%s\"");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_Output);

    // TRACE_TENSOR(2, true, o_Output);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = execute_operator__ai_onnx__einsum__12;
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}