//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__maxroipool__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__maxroipool__1(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_X = searchInputByIndex(ctx, 0);
    //Onnx__TensorProto *i_rois = searchInputByIndex(ctx, 1);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_rois);

    // context_operator__ai_onnx__maxroipool__1 *op_ctx = ctx->executer_context;

    // size_t n_pooled_shape = op_ctx->n_pooled_shape;
    // int64_t* pooled_shape = op_ctx->pooled_shape;
    // float spatial_scale = op_ctx->spatial_scale;

    // TRACE_ARRAY(2, true, pooled_shape, , n_pooled_shape, "%" PRId64);
    // TRACE_VAR(2, true, spatial_scale, "%f");

    //Onnx__TensorProto *o_Y = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}