//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__cast__1;
extern operator_set_opversion opversion_operator__ai_onnx__cast__6;
extern operator_set_opversion opversion_operator__ai_onnx__cast__9;

operator_set_opname opname_operator__ai_onnx__cast = {
    .name = "Cast",
    .opversions = {
        &opversion_operator__ai_onnx__cast__1,
        &opversion_operator__ai_onnx__cast__6,
        &opversion_operator__ai_onnx__cast__9,
        NULL
    }
};