//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__MAX__1_H
# define OPERATOR_OPERATOR__AI_ONNX__MAX__1_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'Max' version 1
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Element-wise max of each of the input tensors. All inputs and outputs must
 * have the same shape and data type.
 * 
 * Constraint T:
 *   Constrain input and output types to float tensors.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Input T data_0:
 *   List of tensors for Max.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Output T max:
 *   Output tensor. Same dimension as inputs.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Attribute INTS consumed_inputs (optional):
 *   legacy optimization attribute.
*
* @since version 1
*
 * @see io/onnx/onnx/defs/math/old.cc:824
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Max
*/

operator_status
prepare_operator__ai_onnx__max__1(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__max__1;

typedef struct {
    size_t n_consumed_inputs;
    int64_t* consumed_inputs;

} context_operator__ai_onnx__max__1;

operator_status
execute_operator__ai_onnx__max__1(
    Onnx__NodeProto *ctx
);

# endif