//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__LESS__9_H
# define OPERATOR_OPERATOR__AI_ONNX__LESS__9_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'Less' version 9
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Returns the tensor resulted from performing the `less` logical operation
 * elementwise on the input tensors `A` and `B` (with Numpy-style broadcasting support).
 * 
 * This operator supports **multidirectional (i.e., Numpy-style) broadcasting**; for more details please check [the doc](Broadcasting.md).
 * 
 * Constraint T:
 *   Constrains input types to all numeric tensors.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_uint16,
 *                  tensor_uint32, tensor_uint64, tensor_uint8
 * 
 * Constraint T1:
 *   Constrains output to boolean tensor.
 *   Allowed Types: tensor_bool
 * Input T A:
 *   First input operand for the logical operator.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_uint16,
 *                  tensor_uint32, tensor_uint64, tensor_uint8
 * 
 * Input T B:
 *   Second input operand for the logical operator.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_uint16,
 *                  tensor_uint32, tensor_uint64, tensor_uint8
 * Output T1 C:
 *   Result tensor.
 *   Allowed Types: tensor_bool

*
* @since version 9
*
 * @see io/onnx/onnx/defs/logical/defs.cc:116
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Less
*/

operator_status
prepare_operator__ai_onnx__less__9(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__less__9;

typedef struct {
// no attributes
} context_operator__ai_onnx__less__9;

operator_status
execute_operator__ai_onnx__less__9(
    Onnx__NodeProto *ctx
);

# endif