//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__rnn__1;
extern operator_set_opversion opversion_operator__ai_onnx__rnn__7;

operator_set_opname opname_operator__ai_onnx__rnn = {
    .name = "RNN",
    .opversions = {
        &opversion_operator__ai_onnx__rnn__1,
        &opversion_operator__ai_onnx__rnn__7,
        NULL
    }
};