//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__SEQUENCEEMPTY__11_H
# define OPERATOR_OPERATOR__AI_ONNX__SEQUENCEEMPTY__11_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'SequenceEmpty' version 11
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Construct an empty tensor sequence, with given data type.
 * 
 * Constraint S:
 *   Constrain output types to any tensor type.
 *   Allowed Types: seq_tensor_bool, seq_tensor_complex128,
 *                  seq_tensor_complex64, seq_tensor_double, seq_tensor_float,
 *                  seq_tensor_float16, seq_tensor_int16, seq_tensor_int32,
 *                  seq_tensor_int64, seq_tensor_int8, seq_tensor_string,
 *                  seq_tensor_uint16, seq_tensor_uint32, seq_tensor_uint64,
 *                  seq_tensor_uint8

 * Output S output:
 *   Empty sequence.
 *   Allowed Types: seq_tensor_bool, seq_tensor_complex128,
 *                  seq_tensor_complex64, seq_tensor_double, seq_tensor_float,
 *                  seq_tensor_float16, seq_tensor_int16, seq_tensor_int32,
 *                  seq_tensor_int64, seq_tensor_int8, seq_tensor_string,
 *                  seq_tensor_uint16, seq_tensor_uint32, seq_tensor_uint64,
 *                  seq_tensor_uint8
 * Attribute INT dtype (optional):
 *   (Optional) The data type of the tensors in the output sequence. The
 *   default type is 'float'.
*
* @since version 11
*
 * @see io/onnx/onnx/defs/sequence/defs.cc:52
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#SequenceEmpty
*/

operator_status
prepare_operator__ai_onnx__sequenceempty__11(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__sequenceempty__11;

typedef struct {
    int64_t dtype;

} context_operator__ai_onnx__sequenceempty__11;

operator_status
execute_operator__ai_onnx__sequenceempty__11(
    Onnx__NodeProto *ctx
);

# endif