//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__randomnormallike__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__randomnormallike__1(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_input = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_input);

    // Onnx__AttributeProto *a_dtype = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"dtype");
    // Onnx__AttributeProto *a_mean = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"mean");
    // Onnx__AttributeProto *a_scale = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"scale");
    // Onnx__AttributeProto *a_seed = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"seed");

    // TRACE_ATTRIBUTE(2, a_dtype, a_dtype);
    // TRACE_ATTRIBUTE(2, a_mean, a_mean);
    // TRACE_ATTRIBUTE(2, a_scale, a_scale);
    // TRACE_ATTRIBUTE(2, a_seed, a_seed);

    Onnx__TensorProto *o_output = searchOutputByIndex(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // int64_t default_dtype = ;
    // float default_mean = ;
    // float default_scale = ;
    // float default_seed = ;

    // context_operator__ai_onnx__randomnormallike__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__randomnormallike__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->dtype = a_dtype?a_dtype->i:default_dtype;
    // op_ctx->mean = a_mean?a_mean->f:default_mean;
    // op_ctx->scale = a_scale?a_scale->f:default_scale;
    // op_ctx->seed = a_seed?a_seed->f:default_seed;

    // TRACE_VAR(2, true, op_ctx->dtype, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->mean, "%f");
    // TRACE_VAR(2, true, op_ctx->scale, "%f");
    // TRACE_VAR(2, true, op_ctx->seed, "%f");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_output);

    // TRACE_TENSOR(2, true, o_output);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = execute_operator__ai_onnx__randomnormallike__1;
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}