//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__constantofshape__9.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__constantofshape__9(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_input = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_input);

    // context_operator__ai_onnx__constantofshape__9 *op_ctx = ctx->executer_context;

    // Onnx__TensorProto* value = op_ctx->value;

    // TRACE_TENSOR(2, true, value);

    //Onnx__TensorProto *o_output = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}