//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__resize__11.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__resize__11(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_X = searchInputByIndex(ctx, 0);
    //Onnx__TensorProto *i_roi = searchInputByIndex(ctx, 1);
    //Onnx__TensorProto *i_scales = searchInputByIndex(ctx, 2);
    //Onnx__TensorProto *i_sizes = searchInputByIndex(ctx, 3);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_roi);
    // TRACE_TENSOR(2, true, i_scales);
    // TRACE_TENSOR(2, sizes, i_sizes);

    // Onnx__AttributeProto *a_coordinate_transformation_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"coordinate_transformation_mode");
    // Onnx__AttributeProto *a_cubic_coeff_a = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"cubic_coeff_a");
    // Onnx__AttributeProto *a_exclude_outside = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"exclude_outside");
    // Onnx__AttributeProto *a_extrapolation_value = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"extrapolation_value");
    // Onnx__AttributeProto *a_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"mode");
    // Onnx__AttributeProto *a_nearest_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nearest_mode");

    // TRACE_ATTRIBUTE(2, a_coordinate_transformation_mode, a_coordinate_transformation_mode);
    // TRACE_ATTRIBUTE(2, a_cubic_coeff_a, a_cubic_coeff_a);
    // TRACE_ATTRIBUTE(2, a_exclude_outside, a_exclude_outside);
    // TRACE_ATTRIBUTE(2, a_extrapolation_value, a_extrapolation_value);
    // TRACE_ATTRIBUTE(2, a_mode, a_mode);
    // TRACE_ATTRIBUTE(2, a_nearest_mode, a_nearest_mode);

    Onnx__TensorProto *o_Y = searchOutputByIndex(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // char* default_coordinate_transformation_mode = ;
    // float default_cubic_coeff_a = ;
    // int64_t default_exclude_outside = ;
    // float default_extrapolation_value = ;
    // char* default_mode = ;
    // char* default_nearest_mode = ;

    // context_operator__ai_onnx__resize__11 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__resize__11));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->coordinate_transformation_mode = a_coordinate_transformation_mode?strndup((char*)a_coordinate_transformation_mode->s.data, a_coordinate_transformation_mode->s.len):default_coordinate_transformation_mode;
    // op_ctx->cubic_coeff_a = a_cubic_coeff_a?a_cubic_coeff_a->f:default_cubic_coeff_a;
    // op_ctx->exclude_outside = a_exclude_outside?a_exclude_outside->i:default_exclude_outside;
    // op_ctx->extrapolation_value = a_extrapolation_value?a_extrapolation_value->f:default_extrapolation_value;
    // op_ctx->mode = a_mode?strndup((char*)a_mode->s.data, a_mode->s.len):default_mode;
    // op_ctx->nearest_mode = a_nearest_mode?strndup((char*)a_nearest_mode->s.data, a_nearest_mode->s.len):default_nearest_mode;

    // TRACE_VAR(2, true, op_ctx->coordinate_transformation_mode, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->cubic_coeff_a, "%f");
    // TRACE_VAR(2, true, op_ctx->exclude_outside, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->extrapolation_value, "%f");
    // TRACE_VAR(2, true, op_ctx->mode, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->nearest_mode, "\"%s\"");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_Y);

    // TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = execute_operator__ai_onnx__resize__11;
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}