//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__CONCAT__4_H
# define OPERATOR_OPERATOR__AI_ONNX__CONCAT__4_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'Concat' version 4
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Concatenate a list of tensors into a single tensor
 * 
 * Constraint T:
 *   Constrain output types to any tensor type.
 *   Allowed Types: tensor_bool, tensor_complex128, tensor_complex64,
 *                  tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_string,
 *                  tensor_uint16, tensor_uint32, tensor_uint64, tensor_uint8
 * Input T inputs:
 *   List of tensors for concatenation
 *   Allowed Types: tensor_bool, tensor_complex128, tensor_complex64,
 *                  tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_string,
 *                  tensor_uint16, tensor_uint32, tensor_uint64, tensor_uint8
 * Output T concat_result:
 *   Concatenated tensor
 *   Allowed Types: tensor_bool, tensor_complex128, tensor_complex64,
 *                  tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_string,
 *                  tensor_uint16, tensor_uint32, tensor_uint64, tensor_uint8
 * Attribute INT axis :
 *   Which axis to concat on
*
* @since version 4
*
 * @see io/onnx/onnx/defs/tensor/old.cc:224
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Concat
*/

operator_status
prepare_operator__ai_onnx__concat__4(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__concat__4;

typedef struct {
    int64_t axis;

} context_operator__ai_onnx__concat__4;

operator_status
execute_operator__ai_onnx__concat__4(
    Onnx__NodeProto *ctx
);

# endif