//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__roialign__10.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__roialign__10(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_rois = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_batch_indices = searchInputByName(ctx, 2);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_rois);
    // TRACE_TENSOR(2, true, i_batch_indices);

    // Onnx__AttributeProto *a_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"mode");
    // Onnx__AttributeProto *a_output_height = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"output_height");
    // Onnx__AttributeProto *a_output_width = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"output_width");
    // Onnx__AttributeProto *a_sampling_ratio = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"sampling_ratio");
    // Onnx__AttributeProto *a_spatial_scale = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"spatial_scale");

    // TRACE_ATTRIBUTE(2, a_mode, a_mode);
    // TRACE_ATTRIBUTE(2, a_output_height, a_output_height);
    // TRACE_ATTRIBUTE(2, a_output_width, a_output_width);
    // TRACE_ATTRIBUTE(2, a_sampling_ratio, a_sampling_ratio);
    // TRACE_ATTRIBUTE(2, a_spatial_scale, a_spatial_scale);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // char* default_mode = ;
    // int64_t default_output_height = ;
    // int64_t default_output_width = ;
    // int64_t default_sampling_ratio = ;
    // float default_spatial_scale = ;

    // context_operator__ai_onnx__roialign__10 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__roialign__10));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->mode = a_mode?strndup((char*)a_mode->s.data, a_mode->s.len):default_mode;
    // op_ctx->output_height = a_output_height?a_output_height->i:default_output_height;
    // op_ctx->output_width = a_output_width?a_output_width->i:default_output_width;
    // op_ctx->sampling_ratio = a_sampling_ratio?a_sampling_ratio->i:default_sampling_ratio;
    // op_ctx->spatial_scale = a_spatial_scale?a_spatial_scale->f:default_spatial_scale;

    // TRACE_VAR(2, true, op_ctx->mode, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->output_height, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->output_width, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->sampling_ratio, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->spatial_scale, "%f");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Y);

    // TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx__roialign__10(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}