//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_preview_training__gradient__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx_preview_training__gradient__1__T1_tensor_float(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_Inputs = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_Inputs);

    // context_operator__ai_onnx_preview_training__gradient__1 *op_ctx = ctx->executer_context;

    // size_t n_xs = op_ctx->n_xs;
    // char** xs = op_ctx->xs;
    // char* y = op_ctx->y;
    // size_t n_zs = op_ctx->n_zs;
    // char** zs = op_ctx->zs;

    // TRACE_ARRAY(2, true, xs, , n_xs, "\"%s\"");
    // TRACE_VAR(2, true, y, "\"%s\"");
    // TRACE_ARRAY(2, true, zs, , n_zs, "\"%s\"");

    // Onnx__TensorProto *o_Outputs = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Outputs);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}