//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__randomnormal__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__randomnormal__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    

    

    // context_operator__ai_onnx__randomnormal__1 *op_ctx = ctx->executer_context;

    // int64_t dtype = op_ctx->dtype;
    // float mean = op_ctx->mean;
    // float scale = op_ctx->scale;
    // float seed = op_ctx->seed;
    // size_t n_shape = op_ctx->n_shape;
    // int64_t* shape = op_ctx->shape;

    // TRACE_VAR(2, true, dtype, "%" PRId64);
    // TRACE_VAR(2, true, mean, "%f");
    // TRACE_VAR(2, true, scale, "%f");
    // TRACE_VAR(2, true, seed, "%f");
    // TRACE_ARRAY(2, true, shape, , n_shape, "%" PRId64);

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}