//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__dynamicquantizelinear__11.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__dynamicquantizelinear__11(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_x = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_x);

    // context_operator__ai_onnx__dynamicquantizelinear__11 *op_ctx = ctx->executer_context;

    

    

    //Onnx__TensorProto *o_y = searchOutputByIndex(ctx, 0);
    //Onnx__TensorProto *o_y_scale = searchOutputByIndex(ctx, 1);
    //Onnx__TensorProto *o_y_zero_point = searchOutputByIndex(ctx, 2);

    // TRACE_TENSOR(2, true, o_y);
    // TRACE_TENSOR(2, true, o_y_scale);
    // TRACE_TENSOR(2, true, o_y_zero_point);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}