//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__svmclassifier__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx_ml__svmclassifier__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_classlabels_ints = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"classlabels_ints");
    // Onnx__AttributeProto *a_classlabels_strings = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"classlabels_strings");
    // Onnx__AttributeProto *a_coefficients = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"coefficients");
    // Onnx__AttributeProto *a_kernel_params = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"kernel_params");
    // Onnx__AttributeProto *a_kernel_type = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"kernel_type");
    // Onnx__AttributeProto *a_post_transform = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"post_transform");
    // Onnx__AttributeProto *a_prob_a = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"prob_a");
    // Onnx__AttributeProto *a_prob_b = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"prob_b");
    // Onnx__AttributeProto *a_rho = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"rho");
    // Onnx__AttributeProto *a_support_vectors = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"support_vectors");
    // Onnx__AttributeProto *a_vectors_per_class = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"vectors_per_class");

    // TRACE_ATTRIBUTE(2, a_classlabels_ints, a_classlabels_ints);
    // TRACE_ATTRIBUTE(2, a_classlabels_strings, a_classlabels_strings);
    // TRACE_ATTRIBUTE(2, a_coefficients, a_coefficients);
    // TRACE_ATTRIBUTE(2, a_kernel_params, a_kernel_params);
    // TRACE_ATTRIBUTE(2, a_kernel_type, a_kernel_type);
    // TRACE_ATTRIBUTE(2, a_post_transform, a_post_transform);
    // TRACE_ATTRIBUTE(2, a_prob_a, a_prob_a);
    // TRACE_ATTRIBUTE(2, a_prob_b, a_prob_b);
    // TRACE_ATTRIBUTE(2, a_rho, a_rho);
    // TRACE_ATTRIBUTE(2, a_support_vectors, a_support_vectors);
    // TRACE_ATTRIBUTE(2, a_vectors_per_class, a_vectors_per_class);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Z = searchOutputByName(ctx, 1);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // size_t default_n_classlabels_ints = ;
    // int64_t* default_classlabels_ints = ;
    // size_t default_n_classlabels_strings = ;
    // char** default_classlabels_strings = ;
    // size_t default_n_coefficients = ;
    // float* default_coefficients = ;
    // size_t default_n_kernel_params = ;
    // float* default_kernel_params = ;
    // char* default_kernel_type = ;
    // char* default_post_transform = ;
    // size_t default_n_prob_a = ;
    // float* default_prob_a = ;
    // size_t default_n_prob_b = ;
    // float* default_prob_b = ;
    // size_t default_n_rho = ;
    // float* default_rho = ;
    // size_t default_n_support_vectors = ;
    // float* default_support_vectors = ;
    // size_t default_n_vectors_per_class = ;
    // int64_t* default_vectors_per_class = ;

    // context_operator__ai_onnx_ml__svmclassifier__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx_ml__svmclassifier__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->n_classlabels_ints = a_classlabels_ints?a_classlabels_ints->n_ints:default_n_classlabels_ints;
    // op_ctx->classlabels_ints = a_classlabels_ints?a_classlabels_ints->ints:ARRAYDUP(default_classlabels_ints,default_n_classlabels_ints);
    // TRACE_FATAL(0, !op_ctx->classlabels_ints, "malloc failed");
    // op_ctx->n_classlabels_strings = a_classlabels_strings?a_classlabels_strings->n_strings:default_n_classlabels_strings;
    // if (a_classlabels_strings) {
    //     op_ctx->classlabels_strings = malloc(a_classlabels_strings->n_strings * sizeof(char*));
    //     TRACE_FATAL(0, !op_ctx->classlabels_strings, "malloc failed");
    //     for (int i = 0; i < a_classlabels_strings->n_strings; i++) { op_ctx->classlabels_strings[i] = strndup((char*)a_classlabels_strings->strings[i].data, a_classlabels_strings->strings[i].len); }
    // } else {
    //     op_ctx->classlabels_strings = a_classlabels_strings?a_classlabels_strings->strings:ARRAYDUP(default_classlabels_strings,default_n_classlabels_strings);
    //     TRACE_FATAL(0, !op_ctx->classlabels_strings, "malloc failed");
    // }
    // op_ctx->n_coefficients = a_coefficients?a_coefficients->n_floats:default_n_coefficients;
    // op_ctx->coefficients = a_coefficients?a_coefficients->floats:ARRAYDUP(default_coefficients,default_n_coefficients);
    // TRACE_FATAL(0, !op_ctx->coefficients, "malloc failed");
    // op_ctx->n_kernel_params = a_kernel_params?a_kernel_params->n_floats:default_n_kernel_params;
    // op_ctx->kernel_params = a_kernel_params?a_kernel_params->floats:ARRAYDUP(default_kernel_params,default_n_kernel_params);
    // TRACE_FATAL(0, !op_ctx->kernel_params, "malloc failed");
    // op_ctx->kernel_type = a_kernel_type?strndup((char*)a_kernel_type->s.data, a_kernel_type->s.len):default_kernel_type;
    // op_ctx->post_transform = a_post_transform?strndup((char*)a_post_transform->s.data, a_post_transform->s.len):default_post_transform;
    // op_ctx->n_prob_a = a_prob_a?a_prob_a->n_floats:default_n_prob_a;
    // op_ctx->prob_a = a_prob_a?a_prob_a->floats:ARRAYDUP(default_prob_a,default_n_prob_a);
    // TRACE_FATAL(0, !op_ctx->prob_a, "malloc failed");
    // op_ctx->n_prob_b = a_prob_b?a_prob_b->n_floats:default_n_prob_b;
    // op_ctx->prob_b = a_prob_b?a_prob_b->floats:ARRAYDUP(default_prob_b,default_n_prob_b);
    // TRACE_FATAL(0, !op_ctx->prob_b, "malloc failed");
    // op_ctx->n_rho = a_rho?a_rho->n_floats:default_n_rho;
    // op_ctx->rho = a_rho?a_rho->floats:ARRAYDUP(default_rho,default_n_rho);
    // TRACE_FATAL(0, !op_ctx->rho, "malloc failed");
    // op_ctx->n_support_vectors = a_support_vectors?a_support_vectors->n_floats:default_n_support_vectors;
    // op_ctx->support_vectors = a_support_vectors?a_support_vectors->floats:ARRAYDUP(default_support_vectors,default_n_support_vectors);
    // TRACE_FATAL(0, !op_ctx->support_vectors, "malloc failed");
    // op_ctx->n_vectors_per_class = a_vectors_per_class?a_vectors_per_class->n_ints:default_n_vectors_per_class;
    // op_ctx->vectors_per_class = a_vectors_per_class?a_vectors_per_class->ints:ARRAYDUP(default_vectors_per_class,default_n_vectors_per_class);
    // TRACE_FATAL(0, !op_ctx->vectors_per_class, "malloc failed");

    // TRACE_ARRAY(2, true, op_ctx->classlabels_ints, , op_ctx->n_classlabels_ints, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->classlabels_strings, , op_ctx->n_classlabels_strings, "\"%s\"");
    // TRACE_ARRAY(2, true, op_ctx->coefficients, , op_ctx->n_coefficients, "%f");
    // TRACE_ARRAY(2, true, op_ctx->kernel_params, , op_ctx->n_kernel_params, "%f");
    // TRACE_VAR(2, true, op_ctx->kernel_type, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->post_transform, "\"%s\"");
    // TRACE_ARRAY(2, true, op_ctx->prob_a, , op_ctx->n_prob_a, "%f");
    // TRACE_ARRAY(2, true, op_ctx->prob_b, , op_ctx->n_prob_b, "%f");
    // TRACE_ARRAY(2, true, op_ctx->rho, , op_ctx->n_rho, "%f");
    // TRACE_ARRAY(2, true, op_ctx->support_vectors, , op_ctx->n_support_vectors, "%f");
    // TRACE_ARRAY(2, true, op_ctx->vectors_per_class, , op_ctx->n_vectors_per_class, "%" PRId64);

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Y);
    // mallocTensorData(o_Z);

    // TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, true, o_Z);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx_ml__svmclassifier__1(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}