//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__gru__3.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__gru__3(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_X = searchInputByIndex(ctx, 0);
    //Onnx__TensorProto *i_W = searchInputByIndex(ctx, 1);
    //Onnx__TensorProto *i_R = searchInputByIndex(ctx, 2);
    //Onnx__TensorProto *i_B = searchInputByIndex(ctx, 3);
    //Onnx__TensorProto *i_sequence_lens = searchInputByIndex(ctx, 4);
    //Onnx__TensorProto *i_initial_h = searchInputByIndex(ctx, 5);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_W);
    // TRACE_TENSOR(2, true, i_R);
    // TRACE_TENSOR(2, B, i_B);
    // TRACE_TENSOR(2, sequence_lens, i_sequence_lens);
    // TRACE_TENSOR(2, initial_h, i_initial_h);

    // Onnx__AttributeProto *a_activation_alpha = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"activation_alpha");
    // Onnx__AttributeProto *a_activation_beta = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"activation_beta");
    // Onnx__AttributeProto *a_activations = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"activations");
    // Onnx__AttributeProto *a_clip = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"clip");
    // Onnx__AttributeProto *a_direction = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"direction");
    // Onnx__AttributeProto *a_hidden_size = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"hidden_size");
    // Onnx__AttributeProto *a_linear_before_reset = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"linear_before_reset");
    // Onnx__AttributeProto *a_output_sequence = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"output_sequence");

    // TRACE_ATTRIBUTE(2, a_activation_alpha, a_activation_alpha);
    // TRACE_ATTRIBUTE(2, a_activation_beta, a_activation_beta);
    // TRACE_ATTRIBUTE(2, a_activations, a_activations);
    // TRACE_ATTRIBUTE(2, a_clip, a_clip);
    // TRACE_ATTRIBUTE(2, a_direction, a_direction);
    // TRACE_ATTRIBUTE(2, a_hidden_size, a_hidden_size);
    // TRACE_ATTRIBUTE(2, a_linear_before_reset, a_linear_before_reset);
    // TRACE_ATTRIBUTE(2, a_output_sequence, a_output_sequence);

    Onnx__TensorProto *o_Y = searchOutputByIndex(ctx, 0);
    Onnx__TensorProto *o_Y_h = searchOutputByIndex(ctx, 1);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // size_t default_n_activation_alpha = ;
    // float* default_activation_alpha = ;
    // size_t default_n_activation_beta = ;
    // float* default_activation_beta = ;
    // size_t default_n_activations = ;
    // char** default_activations = ;
    // float default_clip = ;
    // char* default_direction = ;
    // int64_t default_hidden_size = ;
    // int64_t default_linear_before_reset = ;
    // int64_t default_output_sequence = ;

    // context_operator__ai_onnx__gru__3 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__gru__3));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->n_activation_alpha = a_activation_alpha?a_activation_alpha->n_floats:default_n_activation_alpha;
    // op_ctx->activation_alpha = a_activation_alpha?a_activation_alpha->floats:ARRAYDUP(default_activation_alpha,default_n_activation_alpha);
    // TRACE_FATAL(0, !op_ctx->activation_alpha, "malloc failed");
    // op_ctx->n_activation_beta = a_activation_beta?a_activation_beta->n_floats:default_n_activation_beta;
    // op_ctx->activation_beta = a_activation_beta?a_activation_beta->floats:ARRAYDUP(default_activation_beta,default_n_activation_beta);
    // TRACE_FATAL(0, !op_ctx->activation_beta, "malloc failed");
    // op_ctx->n_activations = a_activations?a_activations->n_strings:default_n_activations;
    // if (a_activations) {
    //     op_ctx->activations = malloc(a_activations->n_strings * sizeof(char*));
    //     TRACE_FATAL(0, !op_ctx->activations, "malloc failed");
    //     for (int i = 0; i < a_activations->n_strings; i++) { op_ctx->activations[i] = strndup((char*)a_activations->strings[i].data, a_activations->strings[i].len); }
    // } else {
    //     op_ctx->activations = a_activations?a_activations->strings:ARRAYDUP(default_activations,default_n_activations);
    //     TRACE_FATAL(0, !op_ctx->activations, "malloc failed");
    // }
    // op_ctx->clip = a_clip?a_clip->f:default_clip;
    // op_ctx->direction = a_direction?strndup((char*)a_direction->s.data, a_direction->s.len):default_direction;
    // op_ctx->hidden_size = a_hidden_size?a_hidden_size->i:default_hidden_size;
    // op_ctx->linear_before_reset = a_linear_before_reset?a_linear_before_reset->i:default_linear_before_reset;
    // op_ctx->output_sequence = a_output_sequence?a_output_sequence->i:default_output_sequence;

    // TRACE_ARRAY(2, true, op_ctx->activation_alpha, , op_ctx->n_activation_alpha, "%f");
    // TRACE_ARRAY(2, true, op_ctx->activation_beta, , op_ctx->n_activation_beta, "%f");
    // TRACE_ARRAY(2, true, op_ctx->activations, , op_ctx->n_activations, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->clip, "%f");
    // TRACE_VAR(2, true, op_ctx->direction, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->hidden_size, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->linear_before_reset, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->output_sequence, "%" PRId64);

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_Y);
    mallocTensorData(o_Y_h);

    // TRACE_TENSOR(2, Y, o_Y);
    // TRACE_TENSOR(2, Y_h, o_Y_h);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = execute_operator__ai_onnx__gru__3;
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}