//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__where__9;

operator_set_opname opname_operator__ai_onnx__where = {
    .name = "Where",
    .opversions = {
        &opversion_operator__ai_onnx__where__9,
        NULL
    }
};