//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__squeeze__1;
extern operator_set_opversion opversion_operator__ai_onnx__squeeze__11;

operator_set_opname opname_operator__ai_onnx__squeeze = {
    .name = "Squeeze",
    .opversions = {
        &opversion_operator__ai_onnx__squeeze__1,
        &opversion_operator__ai_onnx__squeeze__11,
        NULL
    }
};