//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__scaler__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx_ml__scaler__1__T_tensor_int64(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx_ml__scaler__1 *op_ctx = ctx->executer_context;

    // size_t n_offset = op_ctx->n_offset;
    // float* offset = op_ctx->offset;
    // size_t n_scale = op_ctx->n_scale;
    // float* scale = op_ctx->scale;

    // TRACE_ARRAY(2, true, offset, , n_offset, "%f");
    // TRACE_ARRAY(2, true, scale, , n_scale, "%f");

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}