//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__range__11.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__range__11(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_start = searchInputByIndex(ctx, 0);
    //Onnx__TensorProto *i_limit = searchInputByIndex(ctx, 1);
    //Onnx__TensorProto *i_delta = searchInputByIndex(ctx, 2);

    // TRACE_TENSOR(2, true, i_start);
    // TRACE_TENSOR(2, true, i_limit);
    // TRACE_TENSOR(2, true, i_delta);

    // context_operator__ai_onnx__range__11 *op_ctx = ctx->executer_context;

    

    

    //Onnx__TensorProto *o_output = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}