//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__clip__6.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__clip__6(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_input = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_input);

    // Onnx__AttributeProto *a_max = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"max");
    // Onnx__AttributeProto *a_min = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"min");

    // TRACE_ATTRIBUTE(2, a_max, a_max);
    // TRACE_ATTRIBUTE(2, a_min, a_min);

    Onnx__TensorProto *o_output = searchOutputByIndex(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // float default_max = ;
    // float default_min = ;

    // context_operator__ai_onnx__clip__6 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__clip__6));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->max = a_max?a_max->f:default_max;
    // op_ctx->min = a_min?a_min->f:default_min;

    // TRACE_VAR(2, true, op_ctx->max, "%f");
    // TRACE_VAR(2, true, op_ctx->min, "%f");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_output);

    // TRACE_TENSOR(2, true, o_output);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = execute_operator__ai_onnx__clip__6;
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}