//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__mean__6.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__mean__6(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_data_0 = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_data_0);

    

    

    //Onnx__TensorProto *o_mean = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_mean);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__mean__6 *op_ctx = ctx->executer_context;

    

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_mean);
    // free(o_mean->dims);

    TRACE_EXIT(1);
}