//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__prelu__1;
extern operator_set_opversion opversion_operator__ai_onnx__prelu__6;
extern operator_set_opversion opversion_operator__ai_onnx__prelu__7;
extern operator_set_opversion opversion_operator__ai_onnx__prelu__9;

operator_set_opname opname_operator__ai_onnx__prelu = {
    .name = "PRelu",
    .opversions = {
        &opversion_operator__ai_onnx__prelu__1,
        &opversion_operator__ai_onnx__prelu__6,
        &opversion_operator__ai_onnx__prelu__7,
        &opversion_operator__ai_onnx__prelu__9,
        NULL
    }
};