//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__HARDSIGMOID__6_H
# define OPERATOR_OPERATOR__AI_ONNX__HARDSIGMOID__6_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'HardSigmoid' version 6
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * HardSigmoid takes one input data (Tensor<T>) and produces one output data
 * (Tensor<T>) where the HardSigmoid function, y = max(0, min(1, alpha * x + beta)),
 * is applied to the tensor elementwise.
 * 
 * Constraint T:
 *   Constrain input and output types to float tensors.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Input T X:
 *   Input tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Output T Y:
 *   Output tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Attribute FLOAT alpha (optional):
 *   Value of alpha.
 * 
 * Attribute FLOAT beta (optional):
 *   Value of beta.
*
* @since version 6
*
 * @see io/onnx/onnx/defs/math/defs.cc:661
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#HardSigmoid
*/

operator_status
prepare_operator__ai_onnx__hardsigmoid__6(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__hardsigmoid__6;

typedef struct {
    float alpha;
    float beta;

} context_operator__ai_onnx__hardsigmoid__6;

operator_status
execute_operator__ai_onnx__hardsigmoid__6(
    Onnx__NodeProto *ctx
);

# endif