//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__NOT__1_H
# define OPERATOR_OPERATOR__AI_ONNX__NOT__1_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'Not' version 1
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Returns the negation of the input tensor element-wise.
 * 
 * Constraint T:
 *   Constrains input/output to boolean tensors.
 *   Allowed Types: tensor_bool
 * Input T X:
 *   Input tensor
 *   Allowed Types: tensor_bool
 * Output T Y:
 *   Output tensor
 *   Allowed Types: tensor_bool

*
* @since version 1
*
 * @see io/onnx/onnx/defs/logical/defs.cc:158
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Not
*/

operator_status
prepare_operator__ai_onnx__not__1(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__not__1;

typedef struct {
// no attributes
} context_operator__ai_onnx__not__1;

operator_status
execute_operator__ai_onnx__not__1(
    Onnx__NodeProto *ctx
);

# endif