//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__concatfromsequence__11.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__concatfromsequence__11(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_input_sequence = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_input_sequence);

    // context_operator__ai_onnx__concatfromsequence__11 *op_ctx = ctx->executer_context;

    // int64_t axis = op_ctx->axis;
    // int64_t new_axis = op_ctx->new_axis;

    // TRACE_VAR(2, true, axis, "%" PRId64);
    // TRACE_VAR(2, true, new_axis, "%" PRId64);

    // Onnx__TensorProto *o_concat_result = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_concat_result);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}