//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__greater__1;
extern operator_set_opversion opversion_operator__ai_onnx__greater__7;
extern operator_set_opversion opversion_operator__ai_onnx__greater__9;

operator_set_opname opname_operator__ai_onnx__greater = {
    .name = "Greater",
    .opversions = {
        &opversion_operator__ai_onnx__greater__1,
        &opversion_operator__ai_onnx__greater__7,
        &opversion_operator__ai_onnx__greater__9,
        NULL
    }
};