//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__shrink__9.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__shrink__9(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_input = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_input);

    // Onnx__AttributeProto *a_bias = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"bias");
    // Onnx__AttributeProto *a_lambd = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"lambd");

    // TRACE_ATTRIBUTE(2, a_bias, a_bias);
    // TRACE_ATTRIBUTE(2, a_lambd, a_lambd);

    Onnx__TensorProto *o_output = searchOutputByIndex(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // float default_bias = ;
    // float default_lambd = ;

    // context_operator__ai_onnx__shrink__9 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__shrink__9));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->bias = a_bias?a_bias->f:default_bias;
    // op_ctx->lambd = a_lambd?a_lambd->f:default_lambd;

    // TRACE_VAR(2, true, op_ctx->bias, "%f");
    // TRACE_VAR(2, true, op_ctx->lambd, "%f");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_output);

    // TRACE_TENSOR(2, true, o_output);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = execute_operator__ai_onnx__shrink__9;
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}