//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__upsample__7.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__upsample__7(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_X = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"mode");
    // Onnx__AttributeProto *a_scales = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"scales");

    // TRACE_ATTRIBUTE(2, a_mode, a_mode);
    // TRACE_ATTRIBUTE(2, true, a_scales);

    Onnx__TensorProto *o_Y = searchOutputByIndex(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // char* default_mode = ;

    // context_operator__ai_onnx__upsample__7 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__upsample__7));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->mode = a_mode?strndup((char*)a_mode->s.data, a_mode->s.len):default_mode;
    // op_ctx->n_scales = a_scales->n_floats;
    // op_ctx->scales = a_scales->floats;

    // TRACE_VAR(2, true, op_ctx->mode, "\"%s\"");
    // TRACE_ARRAY(2, true, op_ctx->scales, , op_ctx->n_scales, "%f");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_Y);

    // TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = execute_operator__ai_onnx__upsample__7;
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}