//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__softsign__1;

operator_set_opname opname_operator__ai_onnx__softsign = {
    .name = "Softsign",
    .opversions = {
        &opversion_operator__ai_onnx__softsign__1,
        NULL
    }
};