//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__dictvectorizer__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx_ml__dictvectorizer__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_int64_vocabulary = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"int64_vocabulary");
    // Onnx__AttributeProto *a_string_vocabulary = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"string_vocabulary");

    // TRACE_ATTRIBUTE(2, a_int64_vocabulary, a_int64_vocabulary);
    // TRACE_ATTRIBUTE(2, a_string_vocabulary, a_string_vocabulary);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // size_t default_n_int64_vocabulary = ;
    // int64_t* default_int64_vocabulary = ;
    // size_t default_n_string_vocabulary = ;
    // char** default_string_vocabulary = ;

    // context_operator__ai_onnx_ml__dictvectorizer__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx_ml__dictvectorizer__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->n_int64_vocabulary = a_int64_vocabulary?a_int64_vocabulary->n_ints:default_n_int64_vocabulary;
    // op_ctx->int64_vocabulary = a_int64_vocabulary?a_int64_vocabulary->ints:ARRAYDUP(default_int64_vocabulary,default_n_int64_vocabulary);
    // TRACE_FATAL(0, !op_ctx->int64_vocabulary, "malloc failed");
    // op_ctx->n_string_vocabulary = a_string_vocabulary?a_string_vocabulary->n_strings:default_n_string_vocabulary;
    // if (a_string_vocabulary) {
    //     op_ctx->string_vocabulary = malloc(a_string_vocabulary->n_strings * sizeof(char*));
    //     TRACE_FATAL(0, !op_ctx->string_vocabulary, "malloc failed");
    //     for (int i = 0; i < a_string_vocabulary->n_strings; i++) { op_ctx->string_vocabulary[i] = strndup((char*)a_string_vocabulary->strings[i].data, a_string_vocabulary->strings[i].len); }
    // } else {
    //     op_ctx->string_vocabulary = a_string_vocabulary?a_string_vocabulary->strings:ARRAYDUP(default_string_vocabulary,default_n_string_vocabulary);
    //     TRACE_FATAL(0, !op_ctx->string_vocabulary, "malloc failed");
    // }

    // TRACE_ARRAY(2, true, op_ctx->int64_vocabulary, , op_ctx->n_int64_vocabulary, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->string_vocabulary, , op_ctx->n_string_vocabulary, "\"%s\"");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Y);

    // TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx_ml__dictvectorizer__1(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}