//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__pad__2.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__pad__2__T_tensor_float(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_data = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_data);

    // context_operator__ai_onnx__pad__2 *op_ctx = ctx->executer_context;

    // char* mode = op_ctx->mode;
    // size_t n_pads = op_ctx->n_pads;
    // int64_t* pads = op_ctx->pads;
    // float value = op_ctx->value;

    // TRACE_VAR(2, true, mode, "\"%s\"");
    // TRACE_ARRAY(2, true, pads, , n_pads, "%" PRId64);
    // TRACE_VAR(2, true, value, "%f");

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}