//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx_ml__labelencoder__1;
extern operator_set_opversion opversion_operator__ai_onnx_ml__labelencoder__2;

operator_set_opname opname_operator__ai_onnx_ml__labelencoder = {
    .name = "LabelEncoder",
    .opversions = {
        &opversion_operator__ai_onnx_ml__labelencoder__1,
        &opversion_operator__ai_onnx_ml__labelencoder__2,
        NULL
    }
};