//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__resize__10;
extern operator_set_opversion opversion_operator__ai_onnx__resize__11;

operator_set_opname opname_operator__ai_onnx__resize = {
    .name = "Resize",
    .opversions = {
        &opversion_operator__ai_onnx__resize__10,
        &opversion_operator__ai_onnx__resize__11,
        NULL
    }
};