//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__rnn__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__rnn__1(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_X = searchInputByIndex(ctx, 0);
    //Onnx__TensorProto *i_W = searchInputByIndex(ctx, 1);
    //Onnx__TensorProto *i_R = searchInputByIndex(ctx, 2);
    //Onnx__TensorProto *i_B = searchInputByIndex(ctx, 3);
    //Onnx__TensorProto *i_sequence_lens = searchInputByIndex(ctx, 4);
    //Onnx__TensorProto *i_initial_h = searchInputByIndex(ctx, 5);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_W);
    // TRACE_TENSOR(2, true, i_R);
    // TRACE_TENSOR(2, B, i_B);
    // TRACE_TENSOR(2, sequence_lens, i_sequence_lens);
    // TRACE_TENSOR(2, initial_h, i_initial_h);

    // context_operator__ai_onnx__rnn__1 *op_ctx = ctx->executer_context;

    // size_t n_activation_alpha = op_ctx->n_activation_alpha;
    // float* activation_alpha = op_ctx->activation_alpha;
    // size_t n_activation_beta = op_ctx->n_activation_beta;
    // float* activation_beta = op_ctx->activation_beta;
    // size_t n_activations = op_ctx->n_activations;
    // char** activations = op_ctx->activations;
    // float clip = op_ctx->clip;
    // char* direction = op_ctx->direction;
    // int64_t hidden_size = op_ctx->hidden_size;
    // int64_t output_sequence = op_ctx->output_sequence;

    // TRACE_ARRAY(2, true, activation_alpha, , n_activation_alpha, "%f");
    // TRACE_ARRAY(2, true, activation_beta, , n_activation_beta, "%f");
    // TRACE_ARRAY(2, true, activations, , n_activations, "\"%s\"");
    // TRACE_VAR(2, true, clip, "%f");
    // TRACE_VAR(2, true, direction, "\"%s\"");
    // TRACE_VAR(2, true, hidden_size, "%" PRId64);
    // TRACE_VAR(2, true, output_sequence, "%" PRId64);

    //Onnx__TensorProto *o_Y = searchOutputByIndex(ctx, 0);
    //Onnx__TensorProto *o_Y_h = searchOutputByIndex(ctx, 1);

    // TRACE_TENSOR(2, Y, o_Y);
    // TRACE_TENSOR(2, Y_h, o_Y_h);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}