//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__slice__10.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__slice__10(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_data = searchInputByIndex(ctx, 0);
    //Onnx__TensorProto *i_starts = searchInputByIndex(ctx, 1);
    //Onnx__TensorProto *i_ends = searchInputByIndex(ctx, 2);
    //Onnx__TensorProto *i_axes = searchInputByIndex(ctx, 3);
    //Onnx__TensorProto *i_steps = searchInputByIndex(ctx, 4);

    // TRACE_TENSOR(2, true, i_data);
    // TRACE_TENSOR(2, true, i_starts);
    // TRACE_TENSOR(2, true, i_ends);
    // TRACE_TENSOR(2, axes, i_axes);
    // TRACE_TENSOR(2, steps, i_steps);

    // context_operator__ai_onnx__slice__10 *op_ctx = ctx->executer_context;

    

    

    //Onnx__TensorProto *o_output = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}