//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__linearclassifier__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx_ml__linearclassifier__1__T1_tensor_float(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx_ml__linearclassifier__1 *op_ctx = ctx->executer_context;

    // size_t n_classlabels_ints = op_ctx->n_classlabels_ints;
    // int64_t* classlabels_ints = op_ctx->classlabels_ints;
    // size_t n_classlabels_strings = op_ctx->n_classlabels_strings;
    // char** classlabels_strings = op_ctx->classlabels_strings;
    // size_t n_coefficients = op_ctx->n_coefficients;
    // float* coefficients = op_ctx->coefficients;
    // size_t n_intercepts = op_ctx->n_intercepts;
    // float* intercepts = op_ctx->intercepts;
    // int64_t multi_class = op_ctx->multi_class;
    // char* post_transform = op_ctx->post_transform;

    // TRACE_ARRAY(2, true, classlabels_ints, , n_classlabels_ints, "%" PRId64);
    // TRACE_ARRAY(2, true, classlabels_strings, , n_classlabels_strings, "\"%s\"");
    // TRACE_ARRAY(2, true, coefficients, , n_coefficients, "%f");
    // TRACE_ARRAY(2, true, intercepts, , n_intercepts, "%f");
    // TRACE_VAR(2, true, multi_class, "%" PRId64);
    // TRACE_VAR(2, true, post_transform, "\"%s\"");

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Z = searchOutputByName(ctx, 1);

    // TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, true, o_Z);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}