//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__linearclassifier__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx_ml__linearclassifier__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_classlabels_ints = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"classlabels_ints");
    // Onnx__AttributeProto *a_classlabels_strings = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"classlabels_strings");
    // Onnx__AttributeProto *a_coefficients = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"coefficients");
    // Onnx__AttributeProto *a_intercepts = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"intercepts");
    // Onnx__AttributeProto *a_multi_class = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"multi_class");
    // Onnx__AttributeProto *a_post_transform = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"post_transform");

    // TRACE_ATTRIBUTE(2, a_classlabels_ints, a_classlabels_ints);
    // TRACE_ATTRIBUTE(2, a_classlabels_strings, a_classlabels_strings);
    // TRACE_ATTRIBUTE(2, true, a_coefficients);
    // TRACE_ATTRIBUTE(2, a_intercepts, a_intercepts);
    // TRACE_ATTRIBUTE(2, a_multi_class, a_multi_class);
    // TRACE_ATTRIBUTE(2, a_post_transform, a_post_transform);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Z = searchOutputByName(ctx, 1);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // size_t default_n_classlabels_ints = ;
    // int64_t* default_classlabels_ints = ;
    // size_t default_n_classlabels_strings = ;
    // char** default_classlabels_strings = ;
    // size_t default_n_intercepts = ;
    // float* default_intercepts = ;
    // int64_t default_multi_class = ;
    // char* default_post_transform = ;

    // context_operator__ai_onnx_ml__linearclassifier__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx_ml__linearclassifier__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->n_classlabels_ints = a_classlabels_ints?a_classlabels_ints->n_ints:default_n_classlabels_ints;
    // op_ctx->classlabels_ints = a_classlabels_ints?a_classlabels_ints->ints:ARRAYDUP(default_classlabels_ints,default_n_classlabels_ints);
    // TRACE_FATAL(0, !op_ctx->classlabels_ints, "malloc failed");
    // op_ctx->n_classlabels_strings = a_classlabels_strings?a_classlabels_strings->n_strings:default_n_classlabels_strings;
    // if (a_classlabels_strings) {
    //     op_ctx->classlabels_strings = malloc(a_classlabels_strings->n_strings * sizeof(char*));
    //     TRACE_FATAL(0, !op_ctx->classlabels_strings, "malloc failed");
    //     for (int i = 0; i < a_classlabels_strings->n_strings; i++) { op_ctx->classlabels_strings[i] = strndup((char*)a_classlabels_strings->strings[i].data, a_classlabels_strings->strings[i].len); }
    // } else {
    //     op_ctx->classlabels_strings = a_classlabels_strings?a_classlabels_strings->strings:ARRAYDUP(default_classlabels_strings,default_n_classlabels_strings);
    //     TRACE_FATAL(0, !op_ctx->classlabels_strings, "malloc failed");
    // }
    // op_ctx->n_coefficients = a_coefficients->n_floats;
    // op_ctx->coefficients = a_coefficients->floats;
    // op_ctx->n_intercepts = a_intercepts?a_intercepts->n_floats:default_n_intercepts;
    // op_ctx->intercepts = a_intercepts?a_intercepts->floats:ARRAYDUP(default_intercepts,default_n_intercepts);
    // TRACE_FATAL(0, !op_ctx->intercepts, "malloc failed");
    // op_ctx->multi_class = a_multi_class?a_multi_class->i:default_multi_class;
    // op_ctx->post_transform = a_post_transform?strndup((char*)a_post_transform->s.data, a_post_transform->s.len):default_post_transform;

    // TRACE_ARRAY(2, true, op_ctx->classlabels_ints, , op_ctx->n_classlabels_ints, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->classlabels_strings, , op_ctx->n_classlabels_strings, "\"%s\"");
    // TRACE_ARRAY(2, true, op_ctx->coefficients, , op_ctx->n_coefficients, "%f");
    // TRACE_ARRAY(2, true, op_ctx->intercepts, , op_ctx->n_intercepts, "%f");
    // TRACE_VAR(2, true, op_ctx->multi_class, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->post_transform, "\"%s\"");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Y);
    // mallocTensorData(o_Z);

    // TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, true, o_Z);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx_ml__linearclassifier__1(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}