//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__ABS__6_H
# define OPERATOR_OPERATOR__AI_ONNX__ABS__6_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'Abs' version 6
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Absolute takes one input data (Tensor<T>) and produces one output data
 * (Tensor<T>) where the absolute is, y = abs(x), is applied to
 * the tensor elementwise.
 * 
 * Constraint T:
 *   Constrain input and output types to all numeric tensors.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_uint16,
 *                  tensor_uint32, tensor_uint64, tensor_uint8
 * Input T X:
 *   Input tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_uint16,
 *                  tensor_uint32, tensor_uint64, tensor_uint8
 * Output T Y:
 *   Output tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_uint16,
 *                  tensor_uint32, tensor_uint64, tensor_uint8

*
* @since version 6
*
 * @see io/onnx/onnx/defs/math/defs.cc:225
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Abs
*/

operator_status
prepare_operator__ai_onnx__abs__6(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__abs__6;

typedef struct {
// no attributes
} context_operator__ai_onnx__abs__6;

operator_status
execute_operator__ai_onnx__abs__6(
    Onnx__NodeProto *ctx
);

# endif