//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__slice__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__slice__1__T_tensor_string(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_data = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_data);

    // context_operator__ai_onnx__slice__1 *op_ctx = ctx->executer_context;

    // size_t n_axes = op_ctx->n_axes;
    // int64_t* axes = op_ctx->axes;
    // size_t n_ends = op_ctx->n_ends;
    // int64_t* ends = op_ctx->ends;
    // size_t n_starts = op_ctx->n_starts;
    // int64_t* starts = op_ctx->starts;

    // TRACE_ARRAY(2, true, axes, , n_axes, "%" PRId64);
    // TRACE_ARRAY(2, true, ends, , n_ends, "%" PRId64);
    // TRACE_ARRAY(2, true, starts, , n_starts, "%" PRId64);

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}