//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__svmregressor__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx_ml__svmregressor__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_coefficients = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"coefficients");
    // Onnx__AttributeProto *a_kernel_params = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"kernel_params");
    // Onnx__AttributeProto *a_kernel_type = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"kernel_type");
    // Onnx__AttributeProto *a_n_supports = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"n_supports");
    // Onnx__AttributeProto *a_one_class = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"one_class");
    // Onnx__AttributeProto *a_post_transform = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"post_transform");
    // Onnx__AttributeProto *a_rho = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"rho");
    // Onnx__AttributeProto *a_support_vectors = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"support_vectors");

    // TRACE_ATTRIBUTE(2, a_coefficients, a_coefficients);
    // TRACE_ATTRIBUTE(2, a_kernel_params, a_kernel_params);
    // TRACE_ATTRIBUTE(2, a_kernel_type, a_kernel_type);
    // TRACE_ATTRIBUTE(2, a_n_supports, a_n_supports);
    // TRACE_ATTRIBUTE(2, a_one_class, a_one_class);
    // TRACE_ATTRIBUTE(2, a_post_transform, a_post_transform);
    // TRACE_ATTRIBUTE(2, a_rho, a_rho);
    // TRACE_ATTRIBUTE(2, a_support_vectors, a_support_vectors);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // size_t default_n_coefficients = ;
    // float* default_coefficients = ;
    // size_t default_n_kernel_params = ;
    // float* default_kernel_params = ;
    // char* default_kernel_type = ;
    // int64_t default_n_supports = ;
    // int64_t default_one_class = ;
    // char* default_post_transform = ;
    // size_t default_n_rho = ;
    // float* default_rho = ;
    // size_t default_n_support_vectors = ;
    // float* default_support_vectors = ;

    // context_operator__ai_onnx_ml__svmregressor__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx_ml__svmregressor__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->n_coefficients = a_coefficients?a_coefficients->n_floats:default_n_coefficients;
    // op_ctx->coefficients = a_coefficients?a_coefficients->floats:ARRAYDUP(default_coefficients,default_n_coefficients);
    // TRACE_FATAL(0, !op_ctx->coefficients, "malloc failed");
    // op_ctx->n_kernel_params = a_kernel_params?a_kernel_params->n_floats:default_n_kernel_params;
    // op_ctx->kernel_params = a_kernel_params?a_kernel_params->floats:ARRAYDUP(default_kernel_params,default_n_kernel_params);
    // TRACE_FATAL(0, !op_ctx->kernel_params, "malloc failed");
    // op_ctx->kernel_type = a_kernel_type?strndup((char*)a_kernel_type->s.data, a_kernel_type->s.len):default_kernel_type;
    // op_ctx->n_supports = a_n_supports?a_n_supports->i:default_n_supports;
    // op_ctx->one_class = a_one_class?a_one_class->i:default_one_class;
    // op_ctx->post_transform = a_post_transform?strndup((char*)a_post_transform->s.data, a_post_transform->s.len):default_post_transform;
    // op_ctx->n_rho = a_rho?a_rho->n_floats:default_n_rho;
    // op_ctx->rho = a_rho?a_rho->floats:ARRAYDUP(default_rho,default_n_rho);
    // TRACE_FATAL(0, !op_ctx->rho, "malloc failed");
    // op_ctx->n_support_vectors = a_support_vectors?a_support_vectors->n_floats:default_n_support_vectors;
    // op_ctx->support_vectors = a_support_vectors?a_support_vectors->floats:ARRAYDUP(default_support_vectors,default_n_support_vectors);
    // TRACE_FATAL(0, !op_ctx->support_vectors, "malloc failed");

    // TRACE_ARRAY(2, true, op_ctx->coefficients, , op_ctx->n_coefficients, "%f");
    // TRACE_ARRAY(2, true, op_ctx->kernel_params, , op_ctx->n_kernel_params, "%f");
    // TRACE_VAR(2, true, op_ctx->kernel_type, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->n_supports, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->one_class, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->post_transform, "\"%s\"");
    // TRACE_ARRAY(2, true, op_ctx->rho, , op_ctx->n_rho, "%f");
    // TRACE_ARRAY(2, true, op_ctx->support_vectors, , op_ctx->n_support_vectors, "%f");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Y);

    // TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx_ml__svmregressor__1(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}