//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__concat__1;
extern operator_set_opversion opversion_operator__ai_onnx__concat__4;
extern operator_set_opversion opversion_operator__ai_onnx__concat__11;

operator_set_opname opname_operator__ai_onnx__concat = {
    .name = "Concat",
    .opversions = {
        &opversion_operator__ai_onnx__concat__1,
        &opversion_operator__ai_onnx__concat__4,
        &opversion_operator__ai_onnx__concat__11,
        NULL
    }
};