//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__if__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__if__1(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_cond = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_cond);

    // context_operator__ai_onnx__if__1 *op_ctx = ctx->executer_context;

    // Onnx__GraphProto* else_branch = op_ctx->else_branch;
    // Onnx__GraphProto* then_branch = op_ctx->then_branch;

    // TRACE_GRAPH(2, true, else_branch);
    // TRACE_GRAPH(2, true, then_branch);

    //Onnx__TensorProto *o_outputs = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_outputs);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}