//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__zipmap__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx_ml__zipmap__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_classlabels_int64s = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"classlabels_int64s");
    // Onnx__AttributeProto *a_classlabels_strings = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"classlabels_strings");

    // TRACE_ATTRIBUTE(2, a_classlabels_int64s, a_classlabels_int64s);
    // TRACE_ATTRIBUTE(2, a_classlabels_strings, a_classlabels_strings);

    // Onnx__TensorProto *o_Z = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // size_t default_n_classlabels_int64s = ;
    // int64_t* default_classlabels_int64s = ;
    // size_t default_n_classlabels_strings = ;
    // char** default_classlabels_strings = ;

    // context_operator__ai_onnx_ml__zipmap__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx_ml__zipmap__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->n_classlabels_int64s = a_classlabels_int64s?a_classlabels_int64s->n_ints:default_n_classlabels_int64s;
    // op_ctx->classlabels_int64s = a_classlabels_int64s?a_classlabels_int64s->ints:ARRAYDUP(default_classlabels_int64s,default_n_classlabels_int64s);
    // TRACE_FATAL(0, !op_ctx->classlabels_int64s, "malloc failed");
    // op_ctx->n_classlabels_strings = a_classlabels_strings?a_classlabels_strings->n_strings:default_n_classlabels_strings;
    // if (a_classlabels_strings) {
    //     op_ctx->classlabels_strings = malloc(a_classlabels_strings->n_strings * sizeof(char*));
    //     TRACE_FATAL(0, !op_ctx->classlabels_strings, "malloc failed");
    //     for (int i = 0; i < a_classlabels_strings->n_strings; i++) { op_ctx->classlabels_strings[i] = strndup((char*)a_classlabels_strings->strings[i].data, a_classlabels_strings->strings[i].len); }
    // } else {
    //     op_ctx->classlabels_strings = a_classlabels_strings?a_classlabels_strings->strings:ARRAYDUP(default_classlabels_strings,default_n_classlabels_strings);
    //     TRACE_FATAL(0, !op_ctx->classlabels_strings, "malloc failed");
    // }

    // TRACE_ARRAY(2, true, op_ctx->classlabels_int64s, , op_ctx->n_classlabels_int64s, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->classlabels_strings, , op_ctx->n_classlabels_strings, "\"%s\"");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Z);

    // TRACE_TENSOR(2, true, o_Z);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx_ml__zipmap__1(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}