//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__topk__11.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__topk__11(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_X = searchInputByIndex(ctx, 0);
    //Onnx__TensorProto *i_K = searchInputByIndex(ctx, 1);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_K);

    // Onnx__AttributeProto *a_axis = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"axis");
    // Onnx__AttributeProto *a_largest = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"largest");
    // Onnx__AttributeProto *a_sorted = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"sorted");

    // TRACE_ATTRIBUTE(2, a_axis, a_axis);
    // TRACE_ATTRIBUTE(2, a_largest, a_largest);
    // TRACE_ATTRIBUTE(2, a_sorted, a_sorted);

    Onnx__TensorProto *o_Values = searchOutputByIndex(ctx, 0);
    Onnx__TensorProto *o_Indices = searchOutputByIndex(ctx, 1);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // int64_t default_axis = ;
    // int64_t default_largest = ;
    // int64_t default_sorted = ;

    // context_operator__ai_onnx__topk__11 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__topk__11));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->axis = a_axis?a_axis->i:default_axis;
    // op_ctx->largest = a_largest?a_largest->i:default_largest;
    // op_ctx->sorted = a_sorted?a_sorted->i:default_sorted;

    // TRACE_VAR(2, true, op_ctx->axis, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->largest, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->sorted, "%" PRId64);

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_Values);
    mallocTensorData(o_Indices);

    // TRACE_TENSOR(2, true, o_Values);
    // TRACE_TENSOR(2, true, o_Indices);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = execute_operator__ai_onnx__topk__11;
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}