//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__LOG__1_H
# define OPERATOR_OPERATOR__AI_ONNX__LOG__1_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'Log' version 1
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Calculates the natural log of the given input tensor, element-wise.
 * 
 * Constraint T:
 *   Constrain input and output types to float tensors.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Input T input:
 *   Input tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Output T output:
 *   The natural log of the input tensor computed element-wise
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Attribute INTS consumed_inputs (optional):
 *   legacy optimization attribute.
*
* @since version 1
*
 * @see io/onnx/onnx/defs/math/old.cc:628
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Log
*/

operator_status
prepare_operator__ai_onnx__log__1(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__log__1;

typedef struct {
    size_t n_consumed_inputs;
    int64_t* consumed_inputs;

} context_operator__ai_onnx__log__1;

operator_status
execute_operator__ai_onnx__log__1(
    Onnx__NodeProto *ctx
);

# endif