//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__constant__11.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__constant__11(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    

    

    // context_operator__ai_onnx__constant__11 *op_ctx = ctx->executer_context;

    // Onnx__SparseTensorProto* sparse_value = op_ctx->sparse_value;
    // Onnx__TensorProto* value = op_ctx->value;

    // TRACE_VAR(2, true, sparse_value, "%p");
    // TRACE_TENSOR(2, true, value);

    //Onnx__TensorProto *o_output = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}