//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__maxpool__10.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__maxpool__10(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_X = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_auto_pad = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"auto_pad");
    // Onnx__AttributeProto *a_ceil_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"ceil_mode");
    // Onnx__AttributeProto *a_dilations = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"dilations");
    // Onnx__AttributeProto *a_kernel_shape = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"kernel_shape");
    // Onnx__AttributeProto *a_pads = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"pads");
    // Onnx__AttributeProto *a_storage_order = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"storage_order");
    // Onnx__AttributeProto *a_strides = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"strides");

    // TRACE_ATTRIBUTE(2, a_auto_pad, a_auto_pad);
    // TRACE_ATTRIBUTE(2, a_ceil_mode, a_ceil_mode);
    // TRACE_ATTRIBUTE(2, a_dilations, a_dilations);
    // TRACE_ATTRIBUTE(2, true, a_kernel_shape);
    // TRACE_ATTRIBUTE(2, a_pads, a_pads);
    // TRACE_ATTRIBUTE(2, a_storage_order, a_storage_order);
    // TRACE_ATTRIBUTE(2, a_strides, a_strides);

    Onnx__TensorProto *o_Y = searchOutputByIndex(ctx, 0);
    Onnx__TensorProto *o_Indices = searchOutputByIndex(ctx, 1);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // char* default_auto_pad = ;
    // int64_t default_ceil_mode = ;
    // size_t default_n_dilations = ;
    // int64_t* default_dilations = ;
    // size_t default_n_pads = ;
    // int64_t* default_pads = ;
    // int64_t default_storage_order = ;
    // size_t default_n_strides = ;
    // int64_t* default_strides = ;

    // context_operator__ai_onnx__maxpool__10 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__maxpool__10));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->auto_pad = a_auto_pad?strndup((char*)a_auto_pad->s.data, a_auto_pad->s.len):default_auto_pad;
    // op_ctx->ceil_mode = a_ceil_mode?a_ceil_mode->i:default_ceil_mode;
    // op_ctx->n_dilations = a_dilations?a_dilations->n_ints:default_n_dilations;
    // op_ctx->dilations = a_dilations?a_dilations->ints:ARRAYDUP(default_dilations,default_n_dilations);
    // TRACE_FATAL(0, !op_ctx->dilations, "malloc failed");
    // op_ctx->n_kernel_shape = a_kernel_shape->n_ints;
    // op_ctx->kernel_shape = a_kernel_shape->ints;
    // op_ctx->n_pads = a_pads?a_pads->n_ints:default_n_pads;
    // op_ctx->pads = a_pads?a_pads->ints:ARRAYDUP(default_pads,default_n_pads);
    // TRACE_FATAL(0, !op_ctx->pads, "malloc failed");
    // op_ctx->storage_order = a_storage_order?a_storage_order->i:default_storage_order;
    // op_ctx->n_strides = a_strides?a_strides->n_ints:default_n_strides;
    // op_ctx->strides = a_strides?a_strides->ints:ARRAYDUP(default_strides,default_n_strides);
    // TRACE_FATAL(0, !op_ctx->strides, "malloc failed");

    // TRACE_VAR(2, true, op_ctx->auto_pad, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->ceil_mode, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->dilations, , op_ctx->n_dilations, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->kernel_shape, , op_ctx->n_kernel_shape, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->pads, , op_ctx->n_pads, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->storage_order, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->strides, , op_ctx->n_strides, "%" PRId64);

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_Y);
    mallocTensorData(o_Indices);

    // TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, Indices, o_Indices);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = execute_operator__ai_onnx__maxpool__10;
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}