//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__averagepool__1;
extern operator_set_opversion opversion_operator__ai_onnx__averagepool__7;
extern operator_set_opversion opversion_operator__ai_onnx__averagepool__10;
extern operator_set_opversion opversion_operator__ai_onnx__averagepool__11;

operator_set_opname opname_operator__ai_onnx__averagepool = {
    .name = "AveragePool",
    .opversions = {
        &opversion_operator__ai_onnx__averagepool__1,
        &opversion_operator__ai_onnx__averagepool__7,
        &opversion_operator__ai_onnx__averagepool__10,
        &opversion_operator__ai_onnx__averagepool__11,
        NULL
    }
};