//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__stringnormalizer__10.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__stringnormalizer__10(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_X = searchInputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx__stringnormalizer__10 *op_ctx = ctx->executer_context;

    // char* case_change_action = op_ctx->case_change_action;
    // int64_t is_case_sensitive = op_ctx->is_case_sensitive;
    // char* locale = op_ctx->locale;
    // size_t n_stopwords = op_ctx->n_stopwords;
    // char** stopwords = op_ctx->stopwords;

    // TRACE_VAR(2, true, case_change_action, "\"%s\"");
    // TRACE_VAR(2, true, is_case_sensitive, "%" PRId64);
    // TRACE_VAR(2, true, locale, "\"%s\"");
    // TRACE_ARRAY(2, true, stopwords, , n_stopwords, "\"%s\"");

    //Onnx__TensorProto *o_Y = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}