//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__stringnormalizer__10.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__stringnormalizer__10(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_case_change_action = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"case_change_action");
    // Onnx__AttributeProto *a_is_case_sensitive = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"is_case_sensitive");
    // Onnx__AttributeProto *a_locale = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"locale");
    // Onnx__AttributeProto *a_stopwords = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"stopwords");

    // TRACE_ATTRIBUTE(2, a_case_change_action, a_case_change_action);
    // TRACE_ATTRIBUTE(2, a_is_case_sensitive, a_is_case_sensitive);
    // TRACE_ATTRIBUTE(2, a_locale, a_locale);
    // TRACE_ATTRIBUTE(2, a_stopwords, a_stopwords);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // char* default_case_change_action = ;
    // int64_t default_is_case_sensitive = ;
    // char* default_locale = ;
    // size_t default_n_stopwords = ;
    // char** default_stopwords = ;

    // context_operator__ai_onnx__stringnormalizer__10 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__stringnormalizer__10));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->case_change_action = a_case_change_action?strndup((char*)a_case_change_action->s.data, a_case_change_action->s.len):default_case_change_action;
    // op_ctx->is_case_sensitive = a_is_case_sensitive?a_is_case_sensitive->i:default_is_case_sensitive;
    // op_ctx->locale = a_locale?strndup((char*)a_locale->s.data, a_locale->s.len):default_locale;
    // op_ctx->n_stopwords = a_stopwords?a_stopwords->n_strings:default_n_stopwords;
    // if (a_stopwords) {
    //     op_ctx->stopwords = malloc(a_stopwords->n_strings * sizeof(char*));
    //     TRACE_FATAL(0, !op_ctx->stopwords, "malloc failed");
    //     for (int i = 0; i < a_stopwords->n_strings; i++) { op_ctx->stopwords[i] = strndup((char*)a_stopwords->strings[i].data, a_stopwords->strings[i].len); }
    // } else {
    //     op_ctx->stopwords = a_stopwords?a_stopwords->strings:ARRAYDUP(default_stopwords,default_n_stopwords);
    //     TRACE_FATAL(0, !op_ctx->stopwords, "malloc failed");
    // }

    // TRACE_VAR(2, true, op_ctx->case_change_action, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->is_case_sensitive, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->locale, "\"%s\"");
    // TRACE_ARRAY(2, true, op_ctx->stopwords, , op_ctx->n_stopwords, "\"%s\"");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Y);

    // TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx__stringnormalizer__10(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}