//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__WHERE__9_H
# define OPERATOR_OPERATOR__AI_ONNX__WHERE__9_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'Where' version 9
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Return elements, either from X or Y, depending on condition
 *     (with Numpy-style broadcasting support).
 *     Where behaves like numpy.where with three parameters:
 *     https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html
 * 
 * Constraint B:
 *   Constrain to boolean tensors.
 *   Allowed Types: tensor_bool
 * 
 * Constraint T:
 *   Constrain input and output types to all tensor types.
 *   Allowed Types: tensor_bool, tensor_complex128, tensor_complex64,
 *                  tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_string,
 *                  tensor_uint16, tensor_uint32, tensor_uint64, tensor_uint8
 * Input B condition:
 *   When True (nonzero), yield X, otherwise yield Y
 *   Allowed Types: tensor_bool
 * 
 * Input T X:
 *   values selected at indices where condition is True
 *   Allowed Types: tensor_bool, tensor_complex128, tensor_complex64,
 *                  tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_string,
 *                  tensor_uint16, tensor_uint32, tensor_uint64, tensor_uint8
 * 
 * Input T Y:
 *   values selected at indices where condition is False
 *   Allowed Types: tensor_bool, tensor_complex128, tensor_complex64,
 *                  tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_string,
 *                  tensor_uint16, tensor_uint32, tensor_uint64, tensor_uint8
 * Output T output:
 *   Tensor of shape equal to the broadcasted shape of condition, X, and Y.
 *   Allowed Types: tensor_bool, tensor_complex128, tensor_complex64,
 *                  tensor_double, tensor_float, tensor_float16, tensor_int16,
 *                  tensor_int32, tensor_int64, tensor_int8, tensor_string,
 *                  tensor_uint16, tensor_uint32, tensor_uint64, tensor_uint8

 *
 * @since version 9
 *
 * @see io/onnx/onnx/defs/tensor/defs.cc:2152
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Where
 */

operator_status
prepare_operator__ai_onnx__where__9(
    node_context *ctx
);

extern operator_info info_operator__ai_onnx__where__9;

typedef struct {
// no attributes
} context_operator__ai_onnx__where__9;

operator_executer
resolve_operator__ai_onnx__where__9(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__where__9__B_tensor_bool__T_tensor_uint8(
    node_context *ctx
);

# endif