//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__HARDSIGMOID__1_H
# define OPERATOR_OPERATOR__AI_ONNX__HARDSIGMOID__1_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'HardSigmoid' version 1
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * HardSigmoid takes one input data (Tensor<T>) and produces one output data
 * (Tensor<T>) where the HardSigmoid function, y = max(0, min(1, alpha * x + beta)),
 * is applied to the tensor elementwise.
 * 
 * Constraint T:
 *   Constrain input and output types to float tensors.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Input T X:
 *   Input tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Output T Y:
 *   Output tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Attribute FLOAT alpha (optional):
 *   Value of alpha default to 0.2
 * 
 * Attribute FLOAT beta (optional):
 *   Value of beta default to 0.5
 * 
 * Attribute INTS consumed_inputs (optional):
 *   legacy optimization attribute.
*
* @since version 1
*
 * @see io/onnx/onnx/defs/math/old.cc:799
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#HardSigmoid
*/

operator_status
prepare_operator__ai_onnx__hardsigmoid__1(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__hardsigmoid__1;

typedef struct {
    float alpha;
    float beta;
    size_t n_consumed_inputs;
    int64_t* consumed_inputs;

} context_operator__ai_onnx__hardsigmoid__1;

operator_status
execute_operator__ai_onnx__hardsigmoid__1(
    Onnx__NodeProto *ctx
);

# endif