//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__gemm__9.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__gemm__9(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_A = searchInputByIndex(ctx, 0);
    //Onnx__TensorProto *i_B = searchInputByIndex(ctx, 1);
    //Onnx__TensorProto *i_C = searchInputByIndex(ctx, 2);

    // TRACE_TENSOR(2, true, i_A);
    // TRACE_TENSOR(2, true, i_B);
    // TRACE_TENSOR(2, true, i_C);

    // Onnx__AttributeProto *a_alpha = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"alpha");
    // Onnx__AttributeProto *a_beta = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"beta");
    // Onnx__AttributeProto *a_transA = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"transA");
    // Onnx__AttributeProto *a_transB = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"transB");

    // TRACE_ATTRIBUTE(2, a_alpha, a_alpha);
    // TRACE_ATTRIBUTE(2, a_beta, a_beta);
    // TRACE_ATTRIBUTE(2, a_transA, a_transA);
    // TRACE_ATTRIBUTE(2, a_transB, a_transB);

    Onnx__TensorProto *o_Y = searchOutputByIndex(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // float default_alpha = ;
    // float default_beta = ;
    // int64_t default_transA = ;
    // int64_t default_transB = ;

    // context_operator__ai_onnx__gemm__9 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__gemm__9));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->alpha = a_alpha?a_alpha->f:default_alpha;
    // op_ctx->beta = a_beta?a_beta->f:default_beta;
    // op_ctx->transA = a_transA?a_transA->i:default_transA;
    // op_ctx->transB = a_transB?a_transB->i:default_transB;

    // TRACE_VAR(2, true, op_ctx->alpha, "%f");
    // TRACE_VAR(2, true, op_ctx->beta, "%f");
    // TRACE_VAR(2, true, op_ctx->transA, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->transB, "%" PRId64);

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_Y);

    // TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = execute_operator__ai_onnx__gemm__9;
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}