//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__negativeloglikelihoodloss__12.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__negativeloglikelihoodloss__12(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_input = searchInputByIndex(ctx, 0);
    //Onnx__TensorProto *i_target = searchInputByIndex(ctx, 1);
    //Onnx__TensorProto *i_weight = searchInputByIndex(ctx, 2);

    // TRACE_TENSOR(2, true, i_input);
    // TRACE_TENSOR(2, true, i_target);
    // TRACE_TENSOR(2, weight, i_weight);

    // context_operator__ai_onnx__negativeloglikelihoodloss__12 *op_ctx = ctx->executer_context;

    // int64_t ignore_index = op_ctx->ignore_index;
    // char* reduction = op_ctx->reduction;

    // TRACE_VAR(2, true, ignore_index, "%" PRId64);
    // TRACE_VAR(2, true, reduction, "\"%s\"");

    //Onnx__TensorProto *o_loss = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_loss);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}