//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__labelencoder__2.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx_ml__labelencoder__2__T1_tensor_int64(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx_ml__labelencoder__2 *op_ctx = ctx->executer_context;

    // float default_float = op_ctx->default_float;
    // int64_t default_int64 = op_ctx->default_int64;
    // char* default_string = op_ctx->default_string;
    // size_t n_keys_floats = op_ctx->n_keys_floats;
    // float* keys_floats = op_ctx->keys_floats;
    // size_t n_keys_int64s = op_ctx->n_keys_int64s;
    // int64_t* keys_int64s = op_ctx->keys_int64s;
    // size_t n_keys_strings = op_ctx->n_keys_strings;
    // char** keys_strings = op_ctx->keys_strings;
    // size_t n_values_floats = op_ctx->n_values_floats;
    // float* values_floats = op_ctx->values_floats;
    // size_t n_values_int64s = op_ctx->n_values_int64s;
    // int64_t* values_int64s = op_ctx->values_int64s;
    // size_t n_values_strings = op_ctx->n_values_strings;
    // char** values_strings = op_ctx->values_strings;

    // TRACE_VAR(2, true, default_float, "%f");
    // TRACE_VAR(2, true, default_int64, "%" PRId64);
    // TRACE_VAR(2, true, default_string, "\"%s\"");
    // TRACE_ARRAY(2, true, keys_floats, , n_keys_floats, "%f");
    // TRACE_ARRAY(2, true, keys_int64s, , n_keys_int64s, "%" PRId64);
    // TRACE_ARRAY(2, true, keys_strings, , n_keys_strings, "\"%s\"");
    // TRACE_ARRAY(2, true, values_floats, , n_values_floats, "%f");
    // TRACE_ARRAY(2, true, values_int64s, , n_values_int64s, "%" PRId64);
    // TRACE_ARRAY(2, true, values_strings, , n_values_strings, "\"%s\"");

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}