//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__THRESHOLDEDRELU__10_H
# define OPERATOR_OPERATOR__AI_ONNX__THRESHOLDEDRELU__10_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'ThresholdedRelu' version 10
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * ThresholdedRelu takes one input data (Tensor<T>) and produces one output data
 * (Tensor<T>) where the rectified linear function, y = x for x > alpha, y = 0 otherwise,
 * is applied to the tensor elementwise.
 * 
 * Constraint T:
 *   Constrain input and output types to float tensors.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Input T X:
 *   Input tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Output T Y:
 *   Output tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Attribute FLOAT alpha (optional):
 *   Threshold value
*
* @since version 10
*
 * @see io/onnx/onnx/defs/math/defs.cc:360
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#ThresholdedRelu
*/

operator_status
prepare_operator__ai_onnx__thresholdedrelu__10(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__thresholdedrelu__10;

typedef struct {
    float alpha;

} context_operator__ai_onnx__thresholdedrelu__10;

operator_status
execute_operator__ai_onnx__thresholdedrelu__10(
    Onnx__NodeProto *ctx
);

# endif