//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__treeensembleclassifier__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx_ml__treeensembleclassifier__1__T1_tensor_int32(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx_ml__treeensembleclassifier__1 *op_ctx = ctx->executer_context;

    // size_t n_base_values = op_ctx->n_base_values;
    // float* base_values = op_ctx->base_values;
    // size_t n_class_ids = op_ctx->n_class_ids;
    // int64_t* class_ids = op_ctx->class_ids;
    // size_t n_class_nodeids = op_ctx->n_class_nodeids;
    // int64_t* class_nodeids = op_ctx->class_nodeids;
    // size_t n_class_treeids = op_ctx->n_class_treeids;
    // int64_t* class_treeids = op_ctx->class_treeids;
    // size_t n_class_weights = op_ctx->n_class_weights;
    // float* class_weights = op_ctx->class_weights;
    // size_t n_classlabels_int64s = op_ctx->n_classlabels_int64s;
    // int64_t* classlabels_int64s = op_ctx->classlabels_int64s;
    // size_t n_classlabels_strings = op_ctx->n_classlabels_strings;
    // char** classlabels_strings = op_ctx->classlabels_strings;
    // size_t n_nodes_falsenodeids = op_ctx->n_nodes_falsenodeids;
    // int64_t* nodes_falsenodeids = op_ctx->nodes_falsenodeids;
    // size_t n_nodes_featureids = op_ctx->n_nodes_featureids;
    // int64_t* nodes_featureids = op_ctx->nodes_featureids;
    // size_t n_nodes_hitrates = op_ctx->n_nodes_hitrates;
    // float* nodes_hitrates = op_ctx->nodes_hitrates;
    // size_t n_nodes_missing_value_tracks_true = op_ctx->n_nodes_missing_value_tracks_true;
    // int64_t* nodes_missing_value_tracks_true = op_ctx->nodes_missing_value_tracks_true;
    // size_t n_nodes_modes = op_ctx->n_nodes_modes;
    // char** nodes_modes = op_ctx->nodes_modes;
    // size_t n_nodes_nodeids = op_ctx->n_nodes_nodeids;
    // int64_t* nodes_nodeids = op_ctx->nodes_nodeids;
    // size_t n_nodes_treeids = op_ctx->n_nodes_treeids;
    // int64_t* nodes_treeids = op_ctx->nodes_treeids;
    // size_t n_nodes_truenodeids = op_ctx->n_nodes_truenodeids;
    // int64_t* nodes_truenodeids = op_ctx->nodes_truenodeids;
    // size_t n_nodes_values = op_ctx->n_nodes_values;
    // float* nodes_values = op_ctx->nodes_values;
    // char* post_transform = op_ctx->post_transform;

    // TRACE_ARRAY(2, true, base_values, , n_base_values, "%f");
    // TRACE_ARRAY(2, true, class_ids, , n_class_ids, "%" PRId64);
    // TRACE_ARRAY(2, true, class_nodeids, , n_class_nodeids, "%" PRId64);
    // TRACE_ARRAY(2, true, class_treeids, , n_class_treeids, "%" PRId64);
    // TRACE_ARRAY(2, true, class_weights, , n_class_weights, "%f");
    // TRACE_ARRAY(2, true, classlabels_int64s, , n_classlabels_int64s, "%" PRId64);
    // TRACE_ARRAY(2, true, classlabels_strings, , n_classlabels_strings, "\"%s\"");
    // TRACE_ARRAY(2, true, nodes_falsenodeids, , n_nodes_falsenodeids, "%" PRId64);
    // TRACE_ARRAY(2, true, nodes_featureids, , n_nodes_featureids, "%" PRId64);
    // TRACE_ARRAY(2, true, nodes_hitrates, , n_nodes_hitrates, "%f");
    // TRACE_ARRAY(2, true, nodes_missing_value_tracks_true, , n_nodes_missing_value_tracks_true, "%" PRId64);
    // TRACE_ARRAY(2, true, nodes_modes, , n_nodes_modes, "\"%s\"");
    // TRACE_ARRAY(2, true, nodes_nodeids, , n_nodes_nodeids, "%" PRId64);
    // TRACE_ARRAY(2, true, nodes_treeids, , n_nodes_treeids, "%" PRId64);
    // TRACE_ARRAY(2, true, nodes_truenodeids, , n_nodes_truenodeids, "%" PRId64);
    // TRACE_ARRAY(2, true, nodes_values, , n_nodes_values, "%f");
    // TRACE_VAR(2, true, post_transform, "\"%s\"");

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Z = searchOutputByName(ctx, 1);

    // TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, true, o_Z);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}