//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__treeensembleclassifier__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx_ml__treeensembleclassifier__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_base_values = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"base_values");
    // Onnx__AttributeProto *a_class_ids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"class_ids");
    // Onnx__AttributeProto *a_class_nodeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"class_nodeids");
    // Onnx__AttributeProto *a_class_treeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"class_treeids");
    // Onnx__AttributeProto *a_class_weights = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"class_weights");
    // Onnx__AttributeProto *a_classlabels_int64s = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"classlabels_int64s");
    // Onnx__AttributeProto *a_classlabels_strings = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"classlabels_strings");
    // Onnx__AttributeProto *a_nodes_falsenodeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_falsenodeids");
    // Onnx__AttributeProto *a_nodes_featureids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_featureids");
    // Onnx__AttributeProto *a_nodes_hitrates = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_hitrates");
    // Onnx__AttributeProto *a_nodes_missing_value_tracks_true = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_missing_value_tracks_true");
    // Onnx__AttributeProto *a_nodes_modes = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_modes");
    // Onnx__AttributeProto *a_nodes_nodeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_nodeids");
    // Onnx__AttributeProto *a_nodes_treeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_treeids");
    // Onnx__AttributeProto *a_nodes_truenodeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_truenodeids");
    // Onnx__AttributeProto *a_nodes_values = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_values");
    // Onnx__AttributeProto *a_post_transform = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"post_transform");

    // TRACE_ATTRIBUTE(2, a_base_values, a_base_values);
    // TRACE_ATTRIBUTE(2, a_class_ids, a_class_ids);
    // TRACE_ATTRIBUTE(2, a_class_nodeids, a_class_nodeids);
    // TRACE_ATTRIBUTE(2, a_class_treeids, a_class_treeids);
    // TRACE_ATTRIBUTE(2, a_class_weights, a_class_weights);
    // TRACE_ATTRIBUTE(2, a_classlabels_int64s, a_classlabels_int64s);
    // TRACE_ATTRIBUTE(2, a_classlabels_strings, a_classlabels_strings);
    // TRACE_ATTRIBUTE(2, a_nodes_falsenodeids, a_nodes_falsenodeids);
    // TRACE_ATTRIBUTE(2, a_nodes_featureids, a_nodes_featureids);
    // TRACE_ATTRIBUTE(2, a_nodes_hitrates, a_nodes_hitrates);
    // TRACE_ATTRIBUTE(2, a_nodes_missing_value_tracks_true, a_nodes_missing_value_tracks_true);
    // TRACE_ATTRIBUTE(2, a_nodes_modes, a_nodes_modes);
    // TRACE_ATTRIBUTE(2, a_nodes_nodeids, a_nodes_nodeids);
    // TRACE_ATTRIBUTE(2, a_nodes_treeids, a_nodes_treeids);
    // TRACE_ATTRIBUTE(2, a_nodes_truenodeids, a_nodes_truenodeids);
    // TRACE_ATTRIBUTE(2, a_nodes_values, a_nodes_values);
    // TRACE_ATTRIBUTE(2, a_post_transform, a_post_transform);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Z = searchOutputByName(ctx, 1);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // size_t default_n_base_values = ;
    // float* default_base_values = ;
    // size_t default_n_class_ids = ;
    // int64_t* default_class_ids = ;
    // size_t default_n_class_nodeids = ;
    // int64_t* default_class_nodeids = ;
    // size_t default_n_class_treeids = ;
    // int64_t* default_class_treeids = ;
    // size_t default_n_class_weights = ;
    // float* default_class_weights = ;
    // size_t default_n_classlabels_int64s = ;
    // int64_t* default_classlabels_int64s = ;
    // size_t default_n_classlabels_strings = ;
    // char** default_classlabels_strings = ;
    // size_t default_n_nodes_falsenodeids = ;
    // int64_t* default_nodes_falsenodeids = ;
    // size_t default_n_nodes_featureids = ;
    // int64_t* default_nodes_featureids = ;
    // size_t default_n_nodes_hitrates = ;
    // float* default_nodes_hitrates = ;
    // size_t default_n_nodes_missing_value_tracks_true = ;
    // int64_t* default_nodes_missing_value_tracks_true = ;
    // size_t default_n_nodes_modes = ;
    // char** default_nodes_modes = ;
    // size_t default_n_nodes_nodeids = ;
    // int64_t* default_nodes_nodeids = ;
    // size_t default_n_nodes_treeids = ;
    // int64_t* default_nodes_treeids = ;
    // size_t default_n_nodes_truenodeids = ;
    // int64_t* default_nodes_truenodeids = ;
    // size_t default_n_nodes_values = ;
    // float* default_nodes_values = ;
    // char* default_post_transform = ;

    // context_operator__ai_onnx_ml__treeensembleclassifier__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx_ml__treeensembleclassifier__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    // op_ctx->n_base_values = a_base_values?a_base_values->n_floats:default_n_base_values;
    // op_ctx->base_values = a_base_values?a_base_values->floats:ARRAYDUP(default_base_values,default_n_base_values);
    // TRACE_FATAL(0, !op_ctx->base_values, "malloc failed");
    // op_ctx->n_class_ids = a_class_ids?a_class_ids->n_ints:default_n_class_ids;
    // op_ctx->class_ids = a_class_ids?a_class_ids->ints:ARRAYDUP(default_class_ids,default_n_class_ids);
    // TRACE_FATAL(0, !op_ctx->class_ids, "malloc failed");
    // op_ctx->n_class_nodeids = a_class_nodeids?a_class_nodeids->n_ints:default_n_class_nodeids;
    // op_ctx->class_nodeids = a_class_nodeids?a_class_nodeids->ints:ARRAYDUP(default_class_nodeids,default_n_class_nodeids);
    // TRACE_FATAL(0, !op_ctx->class_nodeids, "malloc failed");
    // op_ctx->n_class_treeids = a_class_treeids?a_class_treeids->n_ints:default_n_class_treeids;
    // op_ctx->class_treeids = a_class_treeids?a_class_treeids->ints:ARRAYDUP(default_class_treeids,default_n_class_treeids);
    // TRACE_FATAL(0, !op_ctx->class_treeids, "malloc failed");
    // op_ctx->n_class_weights = a_class_weights?a_class_weights->n_floats:default_n_class_weights;
    // op_ctx->class_weights = a_class_weights?a_class_weights->floats:ARRAYDUP(default_class_weights,default_n_class_weights);
    // TRACE_FATAL(0, !op_ctx->class_weights, "malloc failed");
    // op_ctx->n_classlabels_int64s = a_classlabels_int64s?a_classlabels_int64s->n_ints:default_n_classlabels_int64s;
    // op_ctx->classlabels_int64s = a_classlabels_int64s?a_classlabels_int64s->ints:ARRAYDUP(default_classlabels_int64s,default_n_classlabels_int64s);
    // TRACE_FATAL(0, !op_ctx->classlabels_int64s, "malloc failed");
    // op_ctx->n_classlabels_strings = a_classlabels_strings?a_classlabels_strings->n_strings:default_n_classlabels_strings;
    // if (a_classlabels_strings) {
    //     op_ctx->classlabels_strings = malloc(a_classlabels_strings->n_strings * sizeof(char*));
    //     TRACE_FATAL(0, !op_ctx->classlabels_strings, "malloc failed");
    //     for (int i = 0; i < a_classlabels_strings->n_strings; i++) { op_ctx->classlabels_strings[i] = strndup((char*)a_classlabels_strings->strings[i].data, a_classlabels_strings->strings[i].len); }
    // } else {
    //     op_ctx->classlabels_strings = a_classlabels_strings?a_classlabels_strings->strings:ARRAYDUP(default_classlabels_strings,default_n_classlabels_strings);
    //     TRACE_FATAL(0, !op_ctx->classlabels_strings, "malloc failed");
    // }
    // op_ctx->n_nodes_falsenodeids = a_nodes_falsenodeids?a_nodes_falsenodeids->n_ints:default_n_nodes_falsenodeids;
    // op_ctx->nodes_falsenodeids = a_nodes_falsenodeids?a_nodes_falsenodeids->ints:ARRAYDUP(default_nodes_falsenodeids,default_n_nodes_falsenodeids);
    // TRACE_FATAL(0, !op_ctx->nodes_falsenodeids, "malloc failed");
    // op_ctx->n_nodes_featureids = a_nodes_featureids?a_nodes_featureids->n_ints:default_n_nodes_featureids;
    // op_ctx->nodes_featureids = a_nodes_featureids?a_nodes_featureids->ints:ARRAYDUP(default_nodes_featureids,default_n_nodes_featureids);
    // TRACE_FATAL(0, !op_ctx->nodes_featureids, "malloc failed");
    // op_ctx->n_nodes_hitrates = a_nodes_hitrates?a_nodes_hitrates->n_floats:default_n_nodes_hitrates;
    // op_ctx->nodes_hitrates = a_nodes_hitrates?a_nodes_hitrates->floats:ARRAYDUP(default_nodes_hitrates,default_n_nodes_hitrates);
    // TRACE_FATAL(0, !op_ctx->nodes_hitrates, "malloc failed");
    // op_ctx->n_nodes_missing_value_tracks_true = a_nodes_missing_value_tracks_true?a_nodes_missing_value_tracks_true->n_ints:default_n_nodes_missing_value_tracks_true;
    // op_ctx->nodes_missing_value_tracks_true = a_nodes_missing_value_tracks_true?a_nodes_missing_value_tracks_true->ints:ARRAYDUP(default_nodes_missing_value_tracks_true,default_n_nodes_missing_value_tracks_true);
    // TRACE_FATAL(0, !op_ctx->nodes_missing_value_tracks_true, "malloc failed");
    // op_ctx->n_nodes_modes = a_nodes_modes?a_nodes_modes->n_strings:default_n_nodes_modes;
    // if (a_nodes_modes) {
    //     op_ctx->nodes_modes = malloc(a_nodes_modes->n_strings * sizeof(char*));
    //     TRACE_FATAL(0, !op_ctx->nodes_modes, "malloc failed");
    //     for (int i = 0; i < a_nodes_modes->n_strings; i++) { op_ctx->nodes_modes[i] = strndup((char*)a_nodes_modes->strings[i].data, a_nodes_modes->strings[i].len); }
    // } else {
    //     op_ctx->nodes_modes = a_nodes_modes?a_nodes_modes->strings:ARRAYDUP(default_nodes_modes,default_n_nodes_modes);
    //     TRACE_FATAL(0, !op_ctx->nodes_modes, "malloc failed");
    // }
    // op_ctx->n_nodes_nodeids = a_nodes_nodeids?a_nodes_nodeids->n_ints:default_n_nodes_nodeids;
    // op_ctx->nodes_nodeids = a_nodes_nodeids?a_nodes_nodeids->ints:ARRAYDUP(default_nodes_nodeids,default_n_nodes_nodeids);
    // TRACE_FATAL(0, !op_ctx->nodes_nodeids, "malloc failed");
    // op_ctx->n_nodes_treeids = a_nodes_treeids?a_nodes_treeids->n_ints:default_n_nodes_treeids;
    // op_ctx->nodes_treeids = a_nodes_treeids?a_nodes_treeids->ints:ARRAYDUP(default_nodes_treeids,default_n_nodes_treeids);
    // TRACE_FATAL(0, !op_ctx->nodes_treeids, "malloc failed");
    // op_ctx->n_nodes_truenodeids = a_nodes_truenodeids?a_nodes_truenodeids->n_ints:default_n_nodes_truenodeids;
    // op_ctx->nodes_truenodeids = a_nodes_truenodeids?a_nodes_truenodeids->ints:ARRAYDUP(default_nodes_truenodeids,default_n_nodes_truenodeids);
    // TRACE_FATAL(0, !op_ctx->nodes_truenodeids, "malloc failed");
    // op_ctx->n_nodes_values = a_nodes_values?a_nodes_values->n_floats:default_n_nodes_values;
    // op_ctx->nodes_values = a_nodes_values?a_nodes_values->floats:ARRAYDUP(default_nodes_values,default_n_nodes_values);
    // TRACE_FATAL(0, !op_ctx->nodes_values, "malloc failed");
    // op_ctx->post_transform = a_post_transform?strndup((char*)a_post_transform->s.data, a_post_transform->s.len):default_post_transform;

    // TRACE_ARRAY(2, true, op_ctx->base_values, , op_ctx->n_base_values, "%f");
    // TRACE_ARRAY(2, true, op_ctx->class_ids, , op_ctx->n_class_ids, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->class_nodeids, , op_ctx->n_class_nodeids, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->class_treeids, , op_ctx->n_class_treeids, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->class_weights, , op_ctx->n_class_weights, "%f");
    // TRACE_ARRAY(2, true, op_ctx->classlabels_int64s, , op_ctx->n_classlabels_int64s, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->classlabels_strings, , op_ctx->n_classlabels_strings, "\"%s\"");
    // TRACE_ARRAY(2, true, op_ctx->nodes_falsenodeids, , op_ctx->n_nodes_falsenodeids, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->nodes_featureids, , op_ctx->n_nodes_featureids, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->nodes_hitrates, , op_ctx->n_nodes_hitrates, "%f");
    // TRACE_ARRAY(2, true, op_ctx->nodes_missing_value_tracks_true, , op_ctx->n_nodes_missing_value_tracks_true, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->nodes_modes, , op_ctx->n_nodes_modes, "\"%s\"");
    // TRACE_ARRAY(2, true, op_ctx->nodes_nodeids, , op_ctx->n_nodes_nodeids, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->nodes_treeids, , op_ctx->n_nodes_treeids, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->nodes_truenodeids, , op_ctx->n_nodes_truenodeids, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->nodes_values, , op_ctx->n_nodes_values, "%f");
    // TRACE_VAR(2, true, op_ctx->post_transform, "\"%s\"");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Y);
    // mallocTensorData(o_Z);

    // TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, true, o_Z);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx_ml__treeensembleclassifier__1(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}