//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__sequenceat__11.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__sequenceat__11(
    Onnx__NodeProto *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    //Onnx__TensorProto *i_input_sequence = searchInputByIndex(ctx, 0);
    //Onnx__TensorProto *i_position = searchInputByIndex(ctx, 1);

    // TRACE_TENSOR(2, true, i_input_sequence);
    // TRACE_TENSOR(2, true, i_position);

    

    

    //Onnx__TensorProto *o_tensor = searchOutputByIndex(ctx, 0);

    // TRACE_TENSOR(2, true, o_tensor);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__sequenceat__11 *op_ctx = ctx->executer_context;

    

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_tensor);
    // free(o_tensor->dims);

    TRACE_EXIT(1);
}