name: CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: whatdf
      run: sudo apt-get install libcunit1
    - name: make
      run: gcc -std=c99 -Wall -D DEBUG -o runtest test/tests.c src/*.c -I$HOME/local/include MyProg.c -L$HOME/local/lib -lcunit -lprotobuf-c

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
