//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__tanh__1;
extern operator_set_opversion opversion_operator__ai_onnx__tanh__6;

operator_set_opname opname_operator__ai_onnx__tanh = {
    .name = "Tanh",
    .opversions = {
        &opversion_operator__ai_onnx__tanh__1,
        &opversion_operator__ai_onnx__tanh__6,
        NULL
    }
};