//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__slice__1;
extern operator_set_opversion opversion_operator__ai_onnx__slice__10;
extern operator_set_opversion opversion_operator__ai_onnx__slice__11;

operator_set_opname opname_operator__ai_onnx__slice = {
    .name = "Slice",
    .opversions = {
        &opversion_operator__ai_onnx__slice__1,
        &opversion_operator__ai_onnx__slice__10,
        &opversion_operator__ai_onnx__slice__11,
        NULL
    }
};