//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__RECIPROCAL__6_H
# define OPERATOR_OPERATOR__AI_ONNX__RECIPROCAL__6_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'Reciprocal' version 6
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Reciprocal takes one input data (Tensor<T>) and produces one output data
 * (Tensor<T>) where the reciprocal is, y = 1/x, is applied to
 * the tensor elementwise.
 * 
 * Constraint T:
 *   Constrain input and output types to float tensors.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Input T X:
 *   Input tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Output T Y:
 *   Output tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16

*
* @since version 6
*
 * @see io/onnx/onnx/defs/math/defs.cc:244
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Reciprocal
*/

operator_status
prepare_operator__ai_onnx__reciprocal__6(
    Onnx__NodeProto *ctx
);

extern operator_info info_operator__ai_onnx__reciprocal__6;

typedef struct {
// no attributes
} context_operator__ai_onnx__reciprocal__6;

operator_status
execute_operator__ai_onnx__reciprocal__6(
    Onnx__NodeProto *ctx
);

# endif